### ISSUE TITLE
There's no getSelectedItem () method of the spinner control, any alternative ?

### ISSUE THREAD

**Issue by jhonvidal** [rey5137/material#100]
There's no getSelectedItem () method of the spinner control, any alternative ?.

there is only the methods:
getSelectedItemPosition ()

I need to get the object of the selected item.

please.

 ```java
import com.rey.material.widget.Spinner;
//...
    @InjectView(R.id.spinner_estado)
    Spinner spinner_estado;
//...
 Status item  = (Status) spinner_estado.getSelectedItem();
```

**Comment by rey5137** [comment]
I already added `getSelectedItem()` method to Spinner class in next version (you can try `1.1.1-SNAPSHOT` version). For `1.1.0` version, a workaround is calling:
```java
    spinner.getAdapter().getItem(spinner.getSelectedItemPosition())
```

**Comment by jhonvidal** [comment]
Thaks !

**Comment by hcrespo119** [comment]
thank you very much .
