### ISSUE TITLE
Button icons too big

### ISSUE THREAD

**Issue by CalGH** [rey5137/material#101]
The add button in this library:
![](https://raw.githubusercontent.com/rey5137/Material/master/image/fab_line.gif)

The add button from the official design guideline(http://www.google.com/design/):
![](http://i.imgur.com/JDtdLzT.png?1)

The drawer status indicator, and the left arrow icon are also too big.

Official design guideline: http://www.google.com/design/spec/components/buttons-floating-action-button.html#

**Comment by rey5137** [comment]
If you want, you can style all those attributes (size of icon, line width, ...) as you want. Please check the Wiki for more details.
