### ISSUE TITLE
How can i set a message inside Dialog

### ISSUE THREAD

**Issue by miguelslemos** [rey5137/material#103]
btnenviar.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                final Dialog mDialog = new Dialog(AdicionarEventos.this, R.style.SimpleDialogLight);
                mDialog
                        .title("Você tem certeza?")
                        .positiveAction("Aceitar")

                        .negativeActionClickListener(new OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                Toast.makeText(getApplicationContext(),
                                        "Evento Salvo", Toast.LENGTH_SHORT).show();
                                mDialog.dismiss();
                            }
                        })

                        .negativeAction("CANCEL")
                        .cancelable(true).show();
            }
        });

i only can set title, positiveaction, negative

**Comment by rey5137** [comment]
Please use `SimpleDialog` instead.

**Comment by miguelslemos** [comment]
btnenviar.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                final Dialog SimpleDialog = new SimpleDialog(AdicionarEventos.this, R.style.SimpleDialogLight);
                SimpleDialog
                        .title("Você tem certeza?")
                        .positiveAction("Aceitar")
                        .cancelable(true)


                        .negativeActionClickListener(new OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                Toast.makeText(getApplicationContext(),
                                        "Evento Salvo", Toast.LENGTH_SHORT).show();
                                mDialog.dismiss();
                            }
                        })

                        .negativeAction("CANCEL")
                        .cancelable(true).show();
            }
        });

    }

Ok, i changed but how i can put a message inside Dialog? .message still doesn't work

**Comment by miguelslemos** [comment]
btnenviar.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                final SimpleDialog mDialog = new SimpleDialog(AdicionarEventos.this, R.style.SimpleDialogLight);
                mDialog
                        .title("Você tem certeza?")
                        .positiveAction("Aceitar")
                        .cancelable(true)


                        .negativeActionClickListener(new OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                Toast.makeText(getApplicationContext(),
                                        "Evento Salvo", Toast.LENGTH_SHORT).show();
                                mDialog.dismiss();
                            }
                        })

                        .negativeAction("CANCEL")
                        .cancelable(true).show();
            }
        });

    }

Ok, i changed but still .message doesn't work, how can i put message insde of dialog?

**Comment by rey5137** [comment]
Where do you put `message(CharSequence)` method in the chaining? Because `title(CharSequence)`, `positiveAction(CharSequence)`, ... return a Dialog instead of SimpleDialog so you cannot call `message(CharSequence)` method after this. You should make it the first method is called.

**Comment by miguelslemos** [comment]
Thank you so much for fast reply, now it's working by the way great work

2015-05-14 23:24 GMT-03:00 Rey Pham <notifications@github.com>:

> Where do you put message(CharSequence) method in the chaining? Because
> title(CharSequence), positiveAction(CharSequence), ... return a Dialog
> instead of SimpleDialog so you cannot call message(CharSequence) method
> after this. You should make it the first method is called.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/rey5137/material/issues/103#issuecomment-102225757>.
>



-- 
Miguel Lemos
Graduando em Ciência da Computação

**Comment by miguelslemos** [comment]
Sorry for ask you again but its correctly?
>
> btnenviar.setOnClickListener(new OnClickListener() {
>     @Override
>     public void onClick(View v) {
>         SnackBar.make(AdicionarEventos.this)
>                 .applyStyle(R.style.SnackBarSingleLine)
>                 .text("This is a SnackBar")
>                 .singleLine(true)
>                 .actionText("CLOSE")
>                 .show();
>     }
> });
>
> because when i press the button nothing happen

2015-05-14 23:29 GMT-03:00 Miguel Lemos <miguelslemos@gmail.com>:

> Thank you so much for fast reply, now it's working by the way great work
>
> 2015-05-14 23:24 GMT-03:00 Rey Pham <notifications@github.com>:
>
>> Where do you put message(CharSequence) method in the chaining? Because
>> title(CharSequence), positiveAction(CharSequence), ... return a Dialog
>> instead of SimpleDialog so you cannot call message(CharSequence) method
>> after this. You should make it the first method is called.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rey5137/material/issues/103#issuecomment-102225757>.
>>
>
>
>
> --
> Miguel Lemos
> Graduando em Ciência da Computação
>



-- 
Miguel Lemos
Graduando em Ciência da Computação

**Comment by rey5137** [comment]
`show()` only work when the SnackBar is already attached to a prent view. You should use `show(Activity)` or `show(ViewGroup)`.
