### ISSUE TITLE
FloatActionButton Mini

### ISSUE THREAD

**Issue by muhammad-naderi** [rey5137/material#104]
Trying to make a `mini FloatingActionButton` I set the width and height of the `com.rey.material.widget.FloatingActionButton` to 30dp, but I found that it can not get smaller than a number arround 40 dp , actually do not know if it's the image which prevents the FAB to get smaller of what , but what I think is good to be done is for it to be able to scale down the image inside, so a `mini FAB` can be achieved. 

http://www.google.com/design/spec/components/buttons-floating-action-button.html#

**Comment by rey5137** [comment]
Can you post the xml and code you used?

**Comment by muhammad-naderi** [comment]
xml :

        <com.rey.material.widget.FloatingActionButton
                    style="@style/FloatMini"
                    android:id="@+id/getAccountListBtn"
                    android:layout_width="@dimen/btn_float_mini"
                    android:layout_height="@dimen/btn_float_mini"
                    android:layout_alignBottom="@id/AccountText"
                    android:layout_alignParentEnd="true"
                    app:fab_iconSrc="@drawable/search_account"/>


Style:

    <style name="FloatingWaveColorActionButton" parent="Material.Drawable.Ripple.Wave.Light">
        <item name="rd_rippleColor">#33000000</item>
        <item name="fab_backgroundColor">#FF2196F3</item>
        <item name="fab_elevation">4dp</item>
    </style>
    
    <style name="FloatMini" parent="FloatingWaveColorActionButton">
        <item name="fab_elevation">0dp</item>
    </style>

dimen:

    <dimen name="btn_float_mini">30dp</dimen>

drawable: 

![search_account](https://cloud.githubusercontent.com/assets/8791318/7680935/b1c9390a-fd80-11e4-8db3-4d0722673e26.png)

**Comment by rey5137** [comment]
The size of FAB is set by `fab_radius` attribute, not by `android:layout_width` and `android:layout_height` attribute. Please view [Button](https://github.com/rey5137/material/wiki/Button) wiki page for more available attributes.

**Comment by muhammad-naderi** [comment]
My mistake!

would have been perfect if it was working with height and width too, 

the library is awesome though 
keep up the great work man !
