### ISSUE TITLE
Button text is always in captial letters.

### ISSUE THREAD

**Issue by anupsarode** [rey5137/material#107]
Hello Rey,

I am using the button code in layout xml as follows

<com.rey.material.widget.Button
                style="@style/RaiseWaveColorButtonRippleStyle"
                android:id="@+id/getStartedButton"
                android:layout_width="wrap_content"
                android:layout_height="@dimen/bt_height"
                android:text="Get Started"
                android:textSize="@dimen/button_text_size"
                android:textColor="@color/colorTextOrIcons"
                android:textAppearance="@style/Base.TextAppearance.AppCompat.Button"
                android:paddingLeft="15dp"
                android:paddingRight="15dp" />

The button text I provided is 'Get Started' but everytime when I run the app, I get the text as 'GET STARTED'. Is there any hook using which I can set the text as required? Thanks in advance.

**Comment by rey5137** [comment]
The `com.rey.material.widget.Button` doesn't do anything with Button text. Which Android version did you use to test it? May be you should try to add `android:textAllCaps="false"`.

**Comment by anupsarode** [comment]
Rey, my bad. android:textAllCaps="false" works.

**Comment by Labyrins** [comment]
android:textAppearance="@style/Base.TextAppearance.AppCompat.Button"

This makes all letters in buttons capitailized.
