### ISSUE TITLE
Error:Execution failed for task ':lib:compileReleaseAidl'. > Executor Singleton not started

### ISSUE THREAD

**Issue by sanpark** [rey5137/material#108]
When i import it,it cause this :
Error:Execution failed for task ':lib:compileReleaseAidl'.
> Executor Singleton not started . 
  How to fix it?

**Comment by rey5137** [comment]
How did you import it?

**Comment by sanpark** [comment]
Download the zip.Than Open an existing Android Studio project  in Android Studio.

**Comment by hzy87email** [comment]
@rey5137 I have encountered this problem, import project

**Comment by hzy87email** [comment]
@sanpark Solve the problem，close android studio ，open android studio again，android studio will prompt you again build gradle, build after the operation will

**Comment by hzy87email** [comment]
@rey5137 Thank you for your open source code , so I learned a lot.

**Comment by hzy87email** [comment]
@sanpark  my android studio viersion 1.2.1.1
