### ISSUE TITLE
CheckBox has a left margin

### ISSUE THREAD

**Issue by rocboronat** [rey5137/material#111]
A left margin is added in the CheckBox. It makes near to impossible to align with other Widgets in the same form.

![2015-07-02-10 18](https://cloud.githubusercontent.com/assets/456499/7700845/f2dbe018-fe21-11e4-8762-4cf1cf3c3baa.jpg)

Thanks for your work!

**Comment by rey5137** [comment]
You can change the size of drawable and check box via `cbd_width`, `cbd_height` and `cbd_boxSize` (please view [Switch](https://github.com/rey5137/material/wiki/Switch) page for more details). Even without changing those attribute, you can always set a negative margins to CheckBox (`android:leftMargin="-4dp"` for example).
