### ISSUE TITLE
How to tint the button?

### ISSUE THREAD

**Issue by ppamorim** [rey5137/material#112]
I tried to tint on png, by the code changing the backgroundColor but doesn't work.
I think is more creative to use nine patch only for the shadow. Would you understand this?

**Comment by rey5137** [comment]
Can you explain in more details what you want to achieve?

**Comment by ppamorim** [comment]
I need to change the color of the button.

**Comment by rey5137** [comment]
Can you please post the current xml you used and image of what you want to achieve?
