### ISSUE TITLE
DateTime Picker Dynamically

### ISSUE THREAD

**Issue by patelakshay13890** [rey5137/material#121]
How can I create Date Time Picker dynamically ???

**Comment by rey5137** [comment]
What do you mean by "dynamically"??

**Comment by patelakshay13890** [comment]
By Using DatePickerDialog dynamically create & show.
I want that in my Activity not in fragment as in the given example so how
can I do that ??

**Comment by rey5137** [comment]
If you don't want to use DialogFragment, you can use DatePickerDialog class directly.

**Comment by patelakshay13890** [comment]
But I cannot get it in your Example so can you provide sample code for the same ??

**Comment by patelakshay13890** [comment]
ya but can you provide sample code for that ??

**Comment by silviahisham** [comment]
provide an example for using it in an activity please
