### ISSUE TITLE
Error:Artifact 'Material.jar

### ISSUE THREAD

**Issue by sibidharan** [rey5137/material#126]
I am getting this error while trying to build the project.

```
Error:Artifact 'Material.jar (com.github.rey5137:Material:v1.1.1)' not found.
Searched in the following locations:
    https://jitpack.io/com/github/rey5137/Material/v1.1.1/Material-v1.1.1.jar
```

**Comment by rey5137** [comment]
I have checked jitpack.io and seem like the build process of `v1.1.1` failed due to missing gradle property (That's weird because `v1.1.0` is available). For now you should switch to maven.

**Comment by jitpack-io** [comment]
Indeed, the missing property prevents building. One solution is to do a check before accessing a property  as it's done here: https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L34-L36
Perhaps we can do the same here?

**Comment by sibidharan** [comment]
I found a solution for now.

Searching the same in jcentral by adding dependency from the dependency tab of project settings, my gradle is able to download it from jcentral.
