### ISSUE TITLE
Getting Error in DateDialog in Activity not in Fragment

### ISSUE THREAD

**Issue by patelakshay13890** [rey5137/material#127]
![image](https://cloud.githubusercontent.com/assets/6092323/7782595/18ca1f9c-013d-11e5-9a30-a25664d4aafc.png)

My Code For it in Activity File is :

final DatePickerDialog datePickerDialog = new DatePickerDialog(
					mContext, R.style.DatePicker);
			datePickerDialog.positiveAction("OK").negativeAction("CANCEL");
			datePickerDialog.positiveActionClickListener(new OnClickListener() {
				@Override
				public void onClick(View v) {
					// TODO Auto-generated method stub
					String date = datePickerDialog
							.getFormattedDate(SimpleDateFormat
									.getDateInstance());
					Toast.makeText(mContext, "Date is " + date,
							Toast.LENGTH_SHORT).show();
				}
			});
			datePickerDialog.negativeActionClickListener(new OnClickListener() {
				@Override
				public void onClick(View v) {
					// TODO Auto-generated method stub
					String date = datePickerDialog
							.getFormattedDate(SimpleDateFormat
									.getDateInstance());
					Toast.makeText(mContext, "Date is " + date,
							Toast.LENGTH_SHORT).show();
				}
			});
			datePickerDialog.setOwnerActivity(this);
			datePickerDialog.show();

**Comment by rey5137** [comment]
Seem like you not calling `dateRange()` and `date()` methods of DatePickerDialog class. Unlike DatePickerDialog.Buidler class that setup a default range and selected date if you don't set it, you have to set it to DatePickerDialog class manually.
