### ISSUE TITLE
LineMorphingDrawable statelist - how do I fill up my play button?

### ISSUE THREAD

**Issue by Gintasz** [rey5137/material#128]
I have my play button set up like this:

    
    <state>        
        <points>
        	<item>1</item>
        	<item>1</item>
        	<item>0.3</item>
        	<item>0.5</item>
        	
        	<item>1</item>
        	<item>0</item>
        	<item>0.3</item>
        	<item>0.5</item>
        	
        	<item>1</item>
        	<item>1</item>
        	<item>1</item>
        	<item>0</item>
        </points>
        <links>
            <item>0</item>        	
            <item>1</item>
        	
            <item>0</item>        	
            <item>2</item>
        	
            <item>1</item>        	
            <item>2</item>
        </links>
    </state>

Result looks like this:
![](http://i.imgur.com/0kyYsYp.png)

How do I fill it up?

**Comment by rey5137** [comment]
For now, LineMorphingDrawable can only draw line.
