### ISSUE TITLE
DatePickerDialog strange behaviour

### ISSUE THREAD

**Issue by folivares** [rey5137/material#130]
![date_time_issue](https://cloud.githubusercontent.com/assets/10743930/7788203/16608d72-0232-11e5-8b6d-6fb46d61b928.jpg)

Hi,
when I tap the empty area represented by red rectangles in the left image, the dialog turns as the image on the right.

**Comment by rey5137** [comment]
Which version of library do you used?

**Comment by folivares** [comment]
Yes that's the problem. I've changed from 1.1.0 to 1.1.1 and now works well. Thanks!
