### ISSUE TITLE
AutoCompleteEditText bug.

### ISSUE THREAD

**Issue by don11995** [rey5137/material#132]
Hi! I have a problem with et_autoCompleteMode="single" in EditText. I did all that I found in wiki, autocomplete text appears, but when I try to choose any variant nothing happens. Hints not closing and not do anything when I clicking on them.
My xml:
"<com.rey.material.widget.EditText
            style="@style/Material.Widget.EditText.Light"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/view1"
            app:et_labelTextSize="14sp"
            android:hint="@string/schedules_subjects_settings_add_dialog_name_hint"
            app:et_inputId="@+id/add_subject_name"
            app:et_supportMode="none"
            app:et_labelTextColor="@color/menu_schedule_color"
            app:et_supportTextErrorColor="@color/error_text_color"
            app:et_dividerErrorColor="@color/error_text_color"
            app:et_autoCompleteMode="single"
            android:singleLine="true"
            android:textSize="18sp"
            android:inputType="textCapSentences" />

My code:
ArrayList<String> names = DatabaseAdapter.getInstance(context).getSubjectsNames();
ArrayAdapter<String> namesAdapter = new ArrayAdapter<>(this,R.layout.spinner_layout,names);
com.rey.material.widget.EditText name = (EditText) builder.findViewById(R.id.view1);
name.setAdapter(namesAdapter);

spinner_layout.xml:
<com.don11995.okstudy.classes.RippleTextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    style="@style/RippleTextView"
    android:textAppearance="@android:style/TextAppearance.Medium"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:id="@+id/textView"
    android:text="Spinner"
    android:paddingLeft="8dp"
    android:paddingBottom="16dp"
    android:paddingTop="16dp">
</com.don11995.okstudy.classes.RippleTextView>

RippleTextView.java:
public class RippleTextView extends TextView {
    private RippleManager mRippleManager;

    private void initRipple(Context context, AttributeSet attrs, int defStyleAttr) {
        getRippleManager().onCreate(this, context, attrs, defStyleAttr, R.style.AppTheme);
    }

    protected RippleManager getRippleManager() {
        if (mRippleManager == null) {
            synchronized (RippleManager.class) {
                if (mRippleManager == null)
                    mRippleManager = new RippleManager();
            }
        }

        return mRippleManager;
    }

    public RippleTextView(Context context) {
        super(context);
        initRipple(context, null, 0);
    }

    public RippleTextView(Context context, AttributeSet attrs) {
        super(context, attrs);
        initRipple(context, attrs, 0);
    }

    public RippleTextView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        initRipple(context, attrs, defStyleAttr);
    }

    @Override
    public void setBackgroundDrawable(Drawable drawable) {
        Drawable background = getBackground();
        if(background instanceof RippleDrawable && !(drawable instanceof RippleDrawable))
            ((RippleDrawable) background).setBackgroundDrawable(drawable);
        else
            super.setBackgroundDrawable(drawable);
    }

    @Override
    public void setOnClickListener(OnClickListener l) {
        RippleManager rippleManager = getRippleManager();
        if(l == rippleManager)
            super.setOnClickListener(l);
        else{
            rippleManager.setOnClickListener(l);
            setOnClickListener(rippleManager);
        }
    }

    @Override
    public boolean onTouchEvent(@NonNull MotionEvent event) {
        boolean result = super.onTouchEvent(event);
        return getRippleManager().onTouchEvent(event) || result;
    }
}

If I use simple_list_item_1 from android library (for example) instead of spinner_layout in adapter, this code works fine, but I lose material design on pre lollipop devices. Also, if I change OnTouchEvent in RippleTextView to return always false, it works fine, but has visual artifacts. 

Sorry for my English and thanks for Your attention.

**Comment by rey5137** [comment]
You cannot use RippleEffect on item of dropdown menu because it will override `onItemClick()` event of internal ListView. 
And the library already has a `com.rey.material.widget.TextView` class.
