### ISSUE TITLE
Rendering issue in editor

### ISSUE THREAD

**Issue by Mukul-Sharma** [rey5137/material#139]
Hey, there is a rendering issue when using ProgressView
Missing styles. Is the correct theme chosen for this layout?  
Use the Theme combo box above the layout to choose a different layout, or fix the theme style references.  
Failed to find style with id 0x203000a in current theme

**Comment by andrewpros** [comment]
@rey5137 Have the same problem, any way to fix it, it slightly disturbs designing user interface, the editor is not working then.

**Comment by asep-ridwan** [comment]
have same problem here too, please anyone, would to fix this issue (sorry for my poor english)

**Comment by lvl4fi4** [comment]
@Mukul-Sharma  @andrewpros @asep-ridwan 
You can just ignore the render error bye using `isInEditMode()` till @rey5137 fix this. 
maybe you cant see the exact view but its good for work with editor 
I hope this help you https://github.com/rey5137/material/issues/217

**Comment by rey5137** [comment]
Duplicate of #217
