### ISSUE TITLE
Use Icon in the Dialogue

### ISSUE THREAD

**Issue by patelakshay13890** [rey5137/material#14]
How can I show Icon in the Dialogue box ???

**Comment by rey5137** [comment]
Currently Dialog class doesn't support showing icon.Google Material Design specs doesn't mention that, and I also think It isn't needed (showing app's icon on toolbar also is discourage by Google)

**Comment by patelakshay13890** [comment]
But I have to show Icon in Material Dialogue not in Toolbar ..!!

**Comment by rey5137** [comment]
My point is as Google Material Design specs, Dialog's icon isn't needed. If the need of using icon in Dialog increase, then I'll add it in next version. For now, you may fork it and add a compound drawable to the title textview of dialog yourself.

**Comment by patelakshay13890** [comment]
Okay & waiting for the next version..!!!
And I will try your solution for Change Background Color of Button & Font
Color also..!!
