### ISSUE TITLE
 How to use this library for tablets

### ISSUE THREAD

**Issue by thanhthangnet** [rey5137/material#140]
Widget displays very good with the phone, but in the tablet it was much smaller
How to use this library for tablets.
I must correct your library?

**Comment by rey5137** [comment]
Which widget you want to customize?

**Comment by thanhthangnet** [comment]
I use the datepicker widget, I try to customize them as follows:

---- Dialog.class
![ashampoo_snap_2015 05 31_17h03m36s_004_](https://cloud.githubusercontent.com/assets/11850408/7901531/26da99d8-07b7-11e5-88d0-42acd6b0621e.png)


---- DatePicket.class
![ashampoo_snap_2015 05 31_17h04m17s_005_](https://cloud.githubusercontent.com/assets/11850408/7901532/49826dc6-07b7-11e5-9cce-46fc951db5f0.png)


I get results:
![device-2015-05-31-170706](https://cloud.githubusercontent.com/assets/11850408/7901540/d1b74d2e-07b7-11e5-8119-d1f677c24bd6.png)

How do I correct or not?

**Comment by rey5137** [comment]
There are many style attributes you can use to customize the dialog. Please view [Dialog](https://github.com/rey5137/material/wiki/Dialog) page for more details.
