### ISSUE TITLE
TabPageIndicator without any viewPager.

### ISSUE THREAD

**Issue by mori-honest** [rey5137/material#141]
I want to implement this view with your library but can't find any method to add tabs to TabPageIndicator.
![screen shot 1394-03-11 at 11 17 56](https://cloud.githubusercontent.com/assets/5219339/7908245/2251b18e-0858-11e5-82d1-2521ce08f7a9.png)

Questions:
1- how to add tabs without adding any viewpager to TabPageIndicator( I don't need that, i just want a tabhost to filter my listview.)
2- How to customize tabs style to match the screenshot?
any help is appreciated.tanx

**Comment by rey5137** [comment]
The current `TabPageIndicator` is associated with `ViewPager` directly, so there is no way to use it as you want. But I think you can achieve the view in the screenshot by using `LinearLayout` with horizontal orientation.
