### ISSUE TITLE
ColorStateList resource in Switch 

### ISSUE THREAD

**Issue by terranology** [rey5137/material#143]
Hi there¡ Thanks in advance, 

I'm trying to change the thumb color, trying to set the color as a ColorStateList. I have the .xml in res/color like this:

--selector xmlns:android="http://schemas.android.com/apk/res/android"
    item android:state_checked="true" android:color="@android:color/white" 
    item android:color="@color/switch_thumb" 
--selector

But when the attribute custom:sw_thumbColor="@color/switch_thum_color" make an error:

" Error:(33, 35) No resource found that matches the given name (at 'sw_thumbColor' with value '@color/switch_thum_color'). "

Thanks for your work¡ ;)

**Comment by rey5137** [comment]
The error said that "@color/switch_thum_color" resource isn't found. Did you use a correct name?

**Comment by terranology** [comment]
Sorry, It was my fault because autocomplete doesn't work.
I've done correctly¡ 

Thanx¡
