### ISSUE TITLE
OnClickItem in SimpleDialog for choice item

### ISSUE THREAD

**Issue by terranology** [rey5137/material#145]
Hi there¡

I'm trying to implement an OnClick event for the options to choice (I haven't got accept and cancel), and I don't know how to implement this method, because I cant implement setOnClickListener in the method ((SimpleDialog.Builder)builder).items and also I cant to code ((SimpleDialog.Builder)builder).setItems.

Could you help me please.

Thanks in advance.

**Comment by rey5137** [comment]
You can create an anonymous `SimpleDialog.Buidler` class and override `onSelectionChanged(int, boolean)` method to handle the event (just make sure to call `super.onSelectionChanged()`).
