### ISSUE TITLE
Support for AppCompatActivity 

### ISSUE THREAD

**Issue by nayalabs** [rey5137/material#148]
In my main activity I'm extending AppCompatActivity as ActionBarActivity is depreciated but initializing ToolbarManager errors out as it expects ActionBarActivity.

I know this is not a issue, but would be nice enhancement to support latest android API's and libraries.

**Comment by rey5137** [comment]
I have published `1.2.0-SNAPSHOT` version that changed ActionBarActivity dependency of ToolbarManager class to AppCompatDelegate.
