### ISSUE TITLE
CheckBox colors at runtime

### ISSUE THREAD

**Issue by MazWoz** [rey5137/material#157]
I need to be able to change the colors of Switches (CheckBoxes) at runtime. Is there any way to do this via your library?

Thank you

**Comment by rey5137** [comment]
You can use `applyStyle(int)` method to change style of CheckBox.

**Comment by MazWoz** [comment]
At that point would we just create a style that overloads the color value of the checkbox?

**Comment by rey5137** [comment]
Yes, for now you can do that.

**Comment by MazWoz** [comment]
Awesome, got it working. Now I can't figure out the text color of a checkbox.

**Comment by Juneor** [comment]
can‘t running！

**Comment by wanghailong0408** [comment]
Error:(17) A problem occurred evaluating project ':app'.
> Could not find property 'MATERIAL_KEYSTORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.
大神
