### ISSUE TITLE
Spinner Height in Popup

### ISSUE THREAD

**Issue by peternguyen88** [rey5137/material#158]
I'm having an issue with the height of spinner in a popup. The spinner in your lib cannot show full list of items while the default spinner can. (It is really weird that I can click on the empty space to select the item, it means the item is still there, but does not show).

![device-2015-06-14-200821](https://cloud.githubusercontent.com/assets/6722657/8150034/a6630c88-12d1-11e5-8489-17135e54aa91.png)
![device-2015-06-14-200839](https://cloud.githubusercontent.com/assets/6722657/8150035/a666b432-12d1-11e5-8fe3-5bb8841549d7.png)

**Comment by rey5137** [comment]
I have merged #92 pull request to fix this issue and publish `1.2.0-SNAPSHOT` version. Can you please check it?

**Comment by peternguyen88** [comment]
Thanks, it works. But now the Spinner cannot be instantiated inside Android Studio anymore.
 
![error](https://cloud.githubusercontent.com/assets/6722657/8155420/04bdcf38-133c-11e5-8b82-6bdc7372182f.png)

**Comment by peternguyen88** [comment]
Thank you, it works now.
