### ISSUE TITLE
Slider wiki typo

### ISSUE THREAD

**Issue by formatBCE** [rey5137/material#16]
Hi!
You have typo on Slider Wiki page: com.rey.material.widget.Silder (Silder instead of Slider).
And one more thing: how can i set progress listener for that Slider? Didn't found any specified method in class...

**Comment by rey5137** [comment]
I have fixed the typo. And currently Slider doesn't support progress change listener. I will add it in next version.

**Comment by formatBCE** [comment]
Umm, thanx.
So, what it for without listener? :)
