### ISSUE TITLE
Edittext with android:drawableLeft attribute

### ISSUE THREAD

**Issue by JulieRaiyani** [rey5137/material#163]
Hey ray,

Thanks for such great library,
I want an EditText with image at left side of it, so I used "android:drawableLeft" attribute with Edittext.
It works fine with "android.widget.EditText",but it would not work with "com.rey.material.widget.EditText".I want divider under image which is left to Edittext as like my bellow password Edittext. 

please see at my bellow code .

            <com.rey.material.widget.EditText
                android:id="@+id/edtUserName"
                style="@style/Material.Widget.EditText.Light"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:drawableLeft="@drawable/username"
                android:drawablePadding="10dp"
                android:hint="UserName"
                android:paddingTop="8dp"
                app:et_dividerHeight="2dp"
                app:et_dividerPadding="3dp"
                app:et_supportMode="helper"
                app:et_supportTextErrorColor="@color/error_color" />

            <TextView
                android:layout_width="match_parent"
                android:layout_height="15dp" />

            <EditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:drawableLeft="@drawable/password"
                android:drawablePadding="10dp"
                android:hint="Password" />

Also check bellow image of above output.
![screen shot 2015-06-19 at 7 07 27 pm](https://cloud.githubusercontent.com/assets/12965461/8254705/438aa3ce-16b8-11e5-9a90-9b0fa80dda71.png)

Thanks.. please help me out.

**Comment by rey5137** [comment]
You can set `et_dividerCompoundPadding` attribute to false to make divider not include the padding of compound drawable.

**Comment by JulieRaiyani** [comment]
Thanks a lot :)
