### ISSUE TITLE
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

### ISSUE THREAD

**Issue by SyedRazaMehdiNaqvi** [rey5137/material#165]
when i open the project in my android studio the gradle build failed saying as follows :+1: 

Error:FAILURE: Build failed with an exception.

* What went wrong:
Task '' not found in root project 'material-master'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

what to do is it a bug?

**Comment by johnwatsondev** [comment]
me too. Have you solve this bug ?

**Comment by SyedRazaMehdiNaqvi** [comment]
what I did was to use Git directly to make project instead on first downloading it from git and then import.

Goto File-> New -> Project from version control -> Git

use the git link (https://github.com/rey5137/material) of library to clone and make project, by doing this i successfully run this library project.

Wish you best of luck. If you face any other problem i can email you the zip of the project I successfully executed.

**Comment by johnwatsondev** [comment]
@SyedRazaMehdiNaqvi  Buddy !  Thanks very much for your solution.
I just do it in a another way from your tips. But it built failed.
There are some SNAP_SHOT below.

<img width="406" alt="qq20150809-1" src="https://cloud.githubusercontent.com/assets/12760754/9153534/71fd0a40-3e8f-11e5-8e39-04e5810f3c13.png">
<img width="172" alt="qq20150809-2" src="https://cloud.githubusercontent.com/assets/12760754/9153535/77bc3df2-3e8f-11e5-8c5c-3697ec9fe2b0.png">
<img width="643" alt="qq20150809-3" src="https://cloud.githubusercontent.com/assets/12760754/9153536/7c3ecf8e-3e8f-11e5-9b05-704767e7ba0e.png">

```java
/AndroidContent/AndroidStudio_Workspace/material/app/build.gradle
Error:(17, 1) A problem occurred evaluating project ':app'.
> Could not find property 'MATERIAL_KEYSTORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.
```

Do you have any suggestion ?
Thank in advance!

**Comment by SyedRazaMehdiNaqvi** [comment]
hi @johnwatsondev in your app build.gradle make the following changes

apply plugin: 'com.android.application'

def MATERIAL_KEYSTORE_FILE= "File location goes here"
def MATERIAL_KEYSTORE_PASSWORD= "Store password"
def MATERIAL_KEYSTORE_ALIAS= "Alias to use"
def KEY_PASSWORD= "password to the alias"

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.1"

    defaultConfig {
        applicationId "com.rey.material.demo"
        minSdkVersion 9
        targetSdkVersion 21
        versionCode 3
        versionName "0.0.3"
    }

    signingConfigs {
        release {
            storeFile file(MATERIAL_KEYSTORE_FILE)
            storePassword MATERIAL_KEYSTORE_PASSWORD
            keyAlias MATERIAL_KEYSTORE_ALIAS
            keyPassword MATERIAL_KEYSTORE_PASSWORD
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.2'
    compile 'com.android.support:cardview-v7:21.0.2'
    compile 'com.squareup.picasso:picasso:2.5.0'
    compile project(':lib')
}

**Comment by johnwatsondev** [comment]
@SyedRazaMehdiNaqvi  Thanks very much!
I'm a rookie in Gradle. I appreciate you instructed me patiently.

**Comment by SyedRazaMehdiNaqvi** [comment]
@johnwatsondev no problem hope it helped, glad helping you

**Comment by magdyelsayedomar** [comment]
could you help me ?!
@SyedRazaMehdiNaqvi  
![capture](https://cloud.githubusercontent.com/assets/15814430/12775381/0ee5ec62-ca56-11e5-9673-96ca4d1931a1.PNG)

**Comment by SyedRazaMehdiNaqvi** [comment]
@magdyelsayedomar import the lib folder in your directory parallel to app folder as you are compiling your project with lib folder but in project directory there must be lib folder

**Comment by magdyelsayedomar** [comment]
@SyedRazaMehdiNaqvi  i know that but i don't have it , don't know how to make it , i took this project and open it in android studio , could you help me , by video or other way 
thank you for replying

**Comment by krupalieBizTrait** [comment]
please help i'm getting this error in mac for run emulator
FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleDebug' not found in root project 'android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
ProcessException: Process exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: /Users/chiragganatra/Documents/Mi_Lunch_Money/android/gradlew app:tasks --all --console=auto

**Comment by saurabh-jkm** [comment]
ddd
