### ISSUE TITLE
"dp_yearMin" and "dp_yearMax" attributes for DatePickerStyle not working

### ISSUE THREAD

**Issue by guidufort** [rey5137/material#167]
Hi,
Im using the following code to style the DatePicker:
<code>
builder = new DatePickerDialog.Builder(R.style.DatePickerStyle) {
            @Override...
</code>

And my style  is:

```xml
<style name="DatePickerStyle" parent="Material.App.Dialog.DatePicker.Light">
        <item name="dp_yearMin">1900</item>
        <item name="dp_yearMax">2010</item>
 </style>
```

But I cant get the Min and Max year to work on the year selector list. Can you help me with this problem? Am I doing something wrong?

Thank you, great library by the way.

**Comment by rey5137** [comment]
You should use this construction `public Builder(int styleId, int minDay, int minMonth, int minYear, int maxDay, int maxMonth, int maxYear, int day, int month, int year)`. `dp_yearMin`, `dp_yearMax` only work if you use `DatePicker` class directly.

**Comment by guidufort** [comment]
Thank you, I really appreciate your quick response! Great job man.
