### ISSUE TITLE
Dialog fails when I try to launch it from BroadCastReceiver context

### ISSUE THREAD

**Issue by ferPrieto** [rey5137/material#171]
public class ConnectivityReceiver extends BroadcastReceiver {

        private com.rey.material.app.SimpleDialog mDialog;
        private AdviceConnectionError adviceConnectionError;

        @Override
        public void onReceive(Context context, Intent intent) {
            mDialog  = new com.rey.material.app.SimpleDialog(context);
            mDialog.title(context.getResources().getString(R.string.title_error_connection))
                    .positiveAction("OK")
                    .contentView(R.layout.modal_connection_error)
                    .backgroundColor(-1)
                    .show();

            mDialog.positiveActionClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    context.startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));
                    //TODO: SE ABRE EL SELECTOR DE CONFIGURACIÓN WIFI
                    mDialog.dismiss();
                }
            });
        }
}

When I use it, it fails when the context is passed in the constructor of SimpleDialog. It says: 
RuntimeException: Failed to resolve attribute at index 12

I think it refers to not able to load some style attribute, isn't it?

**Comment by rey5137** [comment]
If you use constructor `SimpleDialog(context)` , it will use `Material.App.Dialog.Simple.Light` style. But this style read `colorControlActivated` attribute from Theme that may not to be set yet in your Context. You should create your own SimpleDialog style, or set theme to context via `setTheme(int)` method.
