### ISSUE TITLE
Does it support ImageButton view via library

### ISSUE THREAD

**Issue by oliguo** [rey5137/material#172]
<com.rey.material.widget.Button
         style="@style/FlatButtonRippleStyle"
            app:rd_enable="true"
            android:id="@+id/next"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:src="@drawable/ic_arrow_back_white"
            android:layout_alignParentLeft="true"
            android:background="@android:color/transparent"
            android:scaleType="fitCenter"
            android:padding="10dp" />

I try to add a image(png) to widget.Button, the button worked but not show image,
how I override or implement to work it?Thanks.

**Comment by rey5137** [comment]
You should use `com.rey.material.widget.ImageButton` instead of `com.rey.material.widget.Button`.

**Comment by oliguo** [comment]
Thanks,but pls add it to wiki https://github.com/rey5137/material/wiki/Button
,because I cannot find any detail about this at first,
Thanks for your reply :+1:

**Comment by FedericoPonzi** [comment]
Still no mention to this :(
