### ISSUE TITLE
How change background color of slider 

### ISSUE THREAD

**Issue by miguelslemos** [rey5137/material#178]
i would like change the background color, how can i change please?
![color](https://cloud.githubusercontent.com/assets/11746181/8392825/eacd330c-1ccd-11e5-9545-52792cdd39f2.png)

**Comment by Yogesh0795** [comment]
have you tried giving style to your slider???
and assigning it ??? in the xml?

**Comment by delebota** [comment]
sl_secondaryColor in the layout's xml.

https://github.com/rey5137/material/wiki/Slider
