### ISSUE TITLE
Button Issue (Lollipop)

### ISSUE THREAD

**Issue by yogeshmadaan100** [rey5137/material#18]
Text on the button is not visible.

**Comment by rey5137** [comment]
Can you please give more details about your devices?

**Comment by yogeshmadaan100** [comment]
Nexus 5
Android Version 5.1

On Sat, Apr 4, 2015 at 2:13 PM, Rey Pham <notifications@github.com> wrote:

> Can you please give more details about your devices?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rey5137/material/issues/18#issuecomment-89529436>.
>



-- 
You didn't hire me , I will fire you!!

Yogesh Madaan
*Tel: +91-7838685554 | W: www.yogeshmadaan.in <http://www.yogeshmadaan.in>*
* <http://www.yogeshmadaan.in>*

**Comment by rey5137** [comment]
It working fine in my genymotion 5.1 emulator. It's weird that there's no others report this bug.

**Comment by yogeshmadaan100** [comment]
For refernce you can consider the screenshot attached in the previous bug
(dialog issue)..

**Comment by rey5137** [comment]
Yes, I noticed it too. But without a real device, I cannot re-procedure this bug.

**Comment by yogeshmadaan100** [comment]
Ok no problem.
I will try to find the bug if I could.. Can you suggest a specific section
which I should consider first.

**Comment by yogeshmadaan100** [comment]
@rey5137  Just repull the changes and its quite weird but its working correctly now. SO i guess we can close it.
