### ISSUE TITLE
DatePicker dialog is blank in OS > L (5.+)

### ISSUE THREAD

**Issue by inteist** [rey5137/material#19]
![](http://i.imgur.com/CDglIqJ.png)

**Comment by rey5137** [comment]
Duplicate of #6.

**Comment by inteist** [comment]
I checked out the most recent `dev` branch which has a comment that it is supposed to fix that but it doesn't.

**Comment by rey5137** [comment]
Please comment on #6 so everyone can follow. Did you already test the fixed apk I upload?
