### ISSUE TITLE
button text

### ISSUE THREAD

**Issue by limulidae** [rey5137/material#192]
why button text are all capitalized?

**Comment by AlessandroGurgel** [comment]
You're able to modify it using android:text.

 <com.rey.material.widget.Button
                    style="@style/RaiseWaveColorButtonRippleStyle"
                    android:id="@+id/button_bt_raise_wave_color"
                    android:layout_width="0dp"
                    android:layout_height="26dp"
                    android:layout_weight="0.4"
                    android:layout_marginTop="5dp"
                    android:layout_marginLeft="10dp"
                    android:layout_marginRight="10dp"
                    android:textColor="#FFFFFFFF"
                    android:textAppearance="@style/Base.TextAppearance.AppCompat.Button"
                    android:text="Adicionar"
                    app:rd_delayClick="afterRelease"/>

**Comment by Labyrins** [comment]
That's because "@style/Base.TextAppearance.AppCompat.Button" is used. Check the 'style.xml' out.

**Comment by fakefacebook** [comment]
I have found the answer !!

add this in your XMl in your Button Tag 

    android:textAllCaps="false"

Enjoy.
