### ISSUE TITLE
How implement listview in dialog?

### ISSUE THREAD

**Issue by Wyllyam** [rey5137/material#194]
I have a listview for inflate in dialog with click for choose a item, how to implements?

**Comment by rey5137** [comment]
You can use `SimpleDialog` to show a choice list ( via `items()` method) or multi-choices list ( via `multiChoiceItems()` method).

**Comment by Wyllyam** [comment]
It would be simpler than this, I need only open a dialog that contains a listview in to display just after the user would click on an item to this list shortly after the close dialogue.

**Comment by artisan-android** [comment]
Yes，I think SimpleDialog provide a method setAdapter
