### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by marbat87** [rey5137/material#20]
I would be very useful be able to set a listener for value change on Slider.
(for example "setOnProgressChangeListener(..)", "setOnValueChangeListener(..)")

Thanks in advance

**Comment by rey5137** [comment]
Yes, I'll add it in next version.

**Comment by Grohden** [comment]
so..without this i should use setOnClickListener? i don't know how to get the values on touch release, and the onClick only gets the release event if the user ends the touch in the view :/

**Comment by rey5137** [comment]
For now you can try 1.01-SNAPSHOT version. I added OnPositionChangeListener interface in this version.

**Comment by rey5137** [comment]
I have released new 1.1.0 version. Please check it.
