### ISSUE TITLE
Unable to change Stroke Color

### ISSUE THREAD

**Issue by sibidharan** [rey5137/material#204]
This is my code. I want the stroke color in white, but it appears in my colorPrimary. Please help.

This is my code.

```xml
<com.rey.material.widget.ProgressView
        android:id="@+id/view"
        android:layout_width="48dp"
        android:layout_height="48dp"
        app:pv_progressStyle="@style/Material.Drawable.CircularProgress"
        app:pv_progressMode="indeterminate"
        app:pv_autostart="true"
        app:pv_circular="true"
        app:cpd_strokeColor="#ffffff"
        android:layout_above="@+id/textView2"
        android:layout_alignLeft="@+id/textView2"
        android:layout_alignStart="@+id/textView2" />
```

**Comment by rey5137** [comment]
You should create your own `CircularProgressDrawable` style (you can extend from `Material.Drawable.CircularProgress` style) and set it to `pv_progressStyle` attribute. `ProgressView` doesn't support attributes of `ProgressDrawable` directly.

**Comment by sibidharan** [comment]
Please explain more, I am an amateur!
