### ISSUE TITLE
CheckBox Text

### ISSUE THREAD

**Issue by FongMi** [rey5137/material#22]
CheckBox text is not middle ??

**Comment by rey5137** [comment]
Can you please provide me more details about this issue? Which device you used? If possible, can you send me some screenshots?

**Comment by FongMi** [comment]
I used Xiaomi2
Rom is Mokee 4.4
 2015/4/5 下午10:48於 "Rey Pham" <notifications@github.com>寫道：

**Comment by mehrad-rafigh** [comment]
You did try settings text gravity to center like android:gravity="center"?

**Comment by FongMi** [comment]
No, CheckBox is add dynamically.
