### ISSUE TITLE
Demo app crash when select contacts with unicode characters

### ISSUE THREAD

**Issue by peternguyen88** [rey5137/material#23]
This library is indeed really amazing. I just installed the demo app and gave it a try, when I selected a contact with unicode characters like Vietnamese in the name, the app crashed. I haven't built the app from source code so cannot give you more information on the crash.

**Comment by rey5137** [comment]
Can you tell me the device you used? May be the crash report already send to my develop console.

**Comment by peternguyen88** [comment]
My phone is LG Optimus G. LGE-F180L

**Comment by rey5137** [comment]
I have added a fix to `dev` branch. The cause of bug is creating BoringLayout with null Metrics parameter.
