### ISSUE TITLE
setOnCancelListener in Dialog not working 

### ISSUE THREAD

**Issue by hmedat2008** [rey5137/material#236]
Hi rey 

Thank you for awesome library, but i have a problem in Dialog class,

I'm trying to set  Cancel Listener to dialog after "onBuildDone" like this:

------------------------------------
@Override
protected void onBuildDone(Dialog dialog) {
        super.onBuildDone(dialog);
        dialog.setOnCancelListener(this);

 }

@Override
public void onCancel(DialogInterface dialog) {
        mActivity.finish();
}
------------------------------------

But onCancel function doesn't call.

This is my issue as simple.

Thanks in advance.

**Comment by rey5137** [comment]
The OnCancelListener you set in `onBuildDone()` method will be override by DialogFragment's listener. You should override `onCancel(DialogInterface)` method of DialogFragment instead.
