### ISSUE TITLE
ArrayAdapter clear() method causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hipczor** [rey5137/material#238]
After clearing ArrayAdapter using `clear()` method, Spinner runs method `setSelection()` where you have code:
```java
if(this.mAdapter != null) {
        position = Math.min(position, this.mAdapter.getCount() - 1);
}
```

When adapter is cleared this code returns -1, sets `mSelectedPosition` to -1, then tries to run 

```java
View v = this.mAdapter.getView(this.mSelectedPosition, this.mRecycler.get(type), this);
```
which causes ArrayIndexOutOfBoundsException

**Comment by rey5137** [comment]
It's fixed and will be available in next release. For now you will have to check it yourself.
