### ISSUE TITLE
How to have full Width button with ripple effect till end ?

### ISSUE THREAD

**Issue by ourdex86** [rey5137/material#24]
Hi,

I am trying to put a button with full screen width in my application. But, ripple effect is only till a bit but not to the complete button. 

How can I achieve that with this library ? 

Also, how to programatically change the button colors with same ripple efffect ?

**Comment by rey5137** [comment]
To make ripple effect fill the whole button, you can set `rd_maxRippleRadius` attribute to `full` enum rather than a dimension value.
About your second question, can you explain more details what you want to achieve?

**Comment by ourdex86** [comment]
Thank you very much for quick response. 

Regarding 2nd question, I want to disable a button (with gray background color ) before editing some text & then when the text field is entered, then I want to enable it with gree background color.

Can you tel me how can I achieve this with your library ?

**Comment by rey5137** [comment]
I have released the new version. Please check ![Button Page](https://github.com/rey5137/material/wiki/Button) for more details.

The `full` enum of `rd_maxRippleRadius` attribute is renamed to `match_view`.

About your 2nd question, you can create a selector xml with 2 states and set it to `android:background` attribute of Button.
