### ISSUE TITLE
EditText

### ISSUE THREAD

**Issue by brunano21** [rey5137/material#241]
I'm trying to use the EditText widget via xml, but I got a 

`Couldn't resolve resource @array/edittext`

Am I missing something?

**Comment by lvl4fi4** [comment]
its in the thems.xml : 

    <array name="edittext">
        <item>@style/LightEditText</item>
        <item>@style/DarkEditText</item>
    </array>

**Comment by brunano21** [comment]
Yeah, I did resolve that. Unfortunately at the beginning I was a bit confused about themes and constants.
