### ISSUE TITLE
Remove ic_launcher images

### ISSUE THREAD

**Issue by nhaarman** [rey5137/material#25]
The library contains `ic_launcher` resources, with the default Android icon (For example https://github.com/rey5137/material/blob/master/lib/src/main/res/drawable-hdpi/ic_launcher.png). Since `ic_launcher` is the common name for the launcher icon, this may lead into trouble for apps using your library.

In my case, I didn't have the `mdpi` launcher icon, which led to your Android `ic_launcher` icon being shown on `mdpi` devices, instead of scaling down my `hdpi` version.

**Comment by rey5137** [comment]
I removed it in next version.
