### ISSUE TITLE
Error:(114, 13) Failed to resolve: com.github.rey5137:material:1.2.1.6-SNAPSHOT

### ISSUE THREAD

**Issue by ArabAgile** [rey5137/material#251]
Just had this error.
Last week no issues with *1.2.1.6-SNAPSHOT*.
Any solution?
Thanks.

**Comment by ArabAgile** [comment]
Solved when removing Android studio and reinstall it.
May be because I updated to 1.4 Beta 3

**Comment by terranology** [comment]
I have been compiling during this week and was ok, but suddenly today had the same error

Failed to resolve: com.github.rey5137:material:1.2.1.6-SNAPSHOT

What can I do?

**Comment by rey5137** [comment]
I have released 1.2.2 version. Pls check it out.
