### ISSUE TITLE
how to set attributes like textSize and textAppearance for buttons

### ISSUE THREAD

**Issue by tatlacas** [rey5137/material#253]
Hi Rey

how do i set attributes like textSize and textAppearance for buttons. the values im setting are being ignored.

Thanks

**Comment by brunano21** [comment]
Hi,
I have the same problem with `editText`s. :-/

**Comment by Labyrins** [comment]
Check "app:v_styleId" in the button attribute. In my case, I didn't control components' style by themes.xml.  I moved all attributes into styles.xml like below and control all components' style.

    <style name="Material.Button" parent="Material.Drawable.Ripple.Touch.Light">
        <item name="android:layout_width">@dimen/bt_width</item>
        <item name="android:layout_height">@dimen/bt_height</item>
        <item name="android:paddingRight">@dimen/button_padding</item>
        <item name="android:paddingLeft">@dimen/button_padding</item>
    </style>

    <style name="Material.Button.Gray" parent="Material.Button">
        <item name="android:background">@drawable/bt_gray_stroke</item>
        <item name="android:textAppearance">@style/Base.TextAppearance.AppCompat.Button</item>
        <item name="android:textColor">@color/material_black_80</item>
        <item name="rd_backgroundColor">@color/gray_dark_alpha_50</item>
    </style>

**Comment by rey5137** [comment]
`v_styleId` attribute is used for dynamic theme feature and it may override any style attribute you set in xml (see [ThemeManager](https://github.com/rey5137/material/wiki/ThemeManager) page for more infomations) . If you don't want this feature, simply remove it.
