### ISSUE TITLE
problem in spinner  No static field Spinner_android_gravity of type I in class

### ISSUE THREAD

**Issue by Mahdiazadbar** [rey5137/material#255]
<com.rey.material.widget.Spinner
                style="@style/Material.Widget.Spinner.Light"
                android:id="@+id/spinner_city"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:entries="@array/Category"
                android:prompt="@array/Category"
                app:rd_style="@style/Material.Drawable.Ripple.Wave.Light"
                app:rd_enable="true"
                app:spn_labelEnable="true"
                app:spn_label="شهر"
                app:spn_arrowSwitchMode="true"
                app:spn_arrowAnimDuration="@android:integer/config_shortAnimTime"
                app:spn_arrowInterpolator="@android:anim/decelerate_interpolator"/>

this is my spiner in lay out. but in set content view have this error 
 Caused by: java.lang.NoSuchFieldError: No static field Spinner_android_gravity of type I in class Lcom/rey/material/R$styleable; or its superclasses (declaration of 'com.rey.material.R$styleable' appears in /data/app/com

pls help me

**Comment by rey5137** [comment]
Duplicate of #222 .

**Comment by 4nd3250n** [comment]
BTW: This issue still does not have a solution.

**Comment by 4nd3250n** [comment]
Will this ever be fixed?
