### ISSUE TITLE
Snackbar with Multi-line

### ISSUE THREAD

**Issue by patelakshay13890** [rey5137/material#257]
How can I show Snackbar with more than 2 lines ??
I wnt to show Snackbar with 3 to 4 lines..So how can I do this ??
In XML 
 app:sb_maxLines="3"
app:sb_lines="3"
neither of these works..!!!!!

**Comment by polapolo** [comment]
From the documentation :
sb_height - The height of SnackBar. Can be dimension value or match_parent or wrap_content enum.

but i cant apply it in my code. I want to apply wrap_content, but height attributes only accept int value. any ideas?

**Comment by rey5137** [comment]
@polapolo `sb_height` accept `match_parent` and `wrap_content` enum. Pls try it.
@patelakshay13890  Can you please show the complete style of your SnackBar?
