### ISSUE TITLE
Proguard build apk issue

### ISSUE THREAD

**Issue by susheel17** [rey5137/material#263]
While trying to generate a signed APK for my app, I am getting this error.

Warning:com.rey.material.drawable.ContactChipDrawable: can't find referenced method 'float ceil(float)' in library class android.util.FloatMath
Warning:com.rey.material.widget.Spinner: can't find referenced field 'int Spinner_android_gravity' in program class com.rey.material.R$styleable
Warning:com.rey.material.widget.Spinner: can't find referenced field 'int Spinner_disableChildrenWhenDisabled' in program class com.rey.material.R$styleable

**Comment by leomarques** [comment]
I also cannot use proguard with this lib, I'v tried adding "-keep class com.rey.material.** { *; }" to proguard but it still does not work, if anyone finds a way to make this work with proguard I'd really appreciate it.

**Comment by SeanSWatkins** [comment]
Just ran into the same issue. I am trying a few things to see what i can get to work. My error is identical to the one mentioned above

**Comment by leomarques** [comment]
If anyonoe finds a solution please post here

**Comment by SeanSWatkins** [comment]
I added a dontwarn for everything in the library. This allowed me to build and, apparently, it is obfuscated and optimised etc. 

-dontwarn com.rey.material.**

That said, I really doubt this is a 'fix.' I don't use the components mentioned in the warning so I figured ignore them wouldn't be an issue.
I am not super handy with proguard yet, I understand the basics but sometimes things go completely differently to what I would think they should do. 

I tried 
-keep class com.rey.material.** { *; }

-keep class com.rey.material.*$* { *; }

etc.

I would really like to know what caused the issue to prevent this in the future.

**Comment by leomarques** [comment]
Thanks Sean, the dontwarn enabled me to build too, but an app would probably crash if it uses the Spinner.

**Comment by 4nd3250n** [comment]
Please see #222.
As it seems it is a known problem, but no solution yet.
The cause is that all *_android_gravity *_prompt and *_disableChildrenWhenDisabled were straight up all removed in 23.
See http://developer.android.com/sdk/support_api_diff/23/changes/android.support.v7.appcompat.R.styleable.html

**Comment by matthewrice345** [comment]
-keep class com.rey.material.** { *; }
-dontwarn com.rey.material.**

Those two lines worked for me, not ideal but it works.

**Comment by rey5137** [comment]
I have released 1.2.2 version. Pls try it.
