### ISSUE TITLE
Null pointer exception when changing ActionTextColor in Dialog

### ISSUE THREAD

**Issue by Deveshs28** [rey5137/material#269]
When changing ActionTextColor(positive & negative button) in either DatePickerDialog or TimePickerDialog, it's giving null pointer exception.
Code:
builder.positiveAction("OK").negativeAction("CANCEL");
builder.getDialog().positiveActionTextColor(Color.parseColor("#FFB125"));
builder.getDialog().negativeActionTextColor(Color.parseColor("#FFB125"));
DialogFragment fragment = DialogFragment.newInstance(builder);
        fragment.show(getSupportFragmentManager(), null);

Also, tried changing button color after showing DialogFragment but still gives 'nullpointerexception'

**Comment by rey5137** [comment]
The `getDialog()` return a Dialog object only after `onCreateDialog()` method of DialogFragment is called. If you want to style the dialog, you can use `style(int)` method, or override `onBuildDone(Dialog)` method.
