### ISSUE TITLE
Error appearance in spinner after changing adapter

### ISSUE THREAD

**Issue by enginebai** [rey5137/material#271]
#### Here is my purpose:
I have two spinner to represent city and town selection, once the user select the city (first spinner) then change the second spinner to list the towns in this city.

#### Code
```java
mSpinnerCity.setOnItemSelectedListener(new Spinner.OnItemSelectedListener() {
    @Override
    public void onItemSelected(Spinner parent, View view, int position, long id) {
        String city = (String)parent.getSelectedItem();
        if (!mRegionMap.get(city).isEmpty())
            mSpinnerArea.setAdapter(new ArrayAdapter<>(NewEventActivity.this,
                android.R.layout.simple_spinner_dropdown_item, new ArrayList<>(mRegionMap.get(city))));
        else
            // for the city has no area
            mSpinnerArea.setAdapter(new ArrayAdapter<>(NewEventActivity.this,
                    android.R.layout.simple_spinner_dropdown_item, new String[]{""}));
    }
});
```

#### Problem
* Error appearance of the second spinner after selecting a city and display the towns in the second spinner.
![1](https://cloud.githubusercontent.com/assets/3387462/10266023/950c3660-6a7b-11e5-8750-a629032c1b3b.png)
* Normal appearance after selecting one item in the second spinner
![2](https://cloud.githubusercontent.com/assets/3387462/10266044/6bd2eb8a-6a7c-11e5-99f1-1daf2734268b.png)

**Comment by rey5137** [comment]
I have fixed this issue. It happens due to incorrect calculating of Spinner's baseline. For current version, may be you should set `android:baselineAligned="false"` to the LinearLayout.

**Comment by sushant015** [comment]
Here is my purpose:

I have two spinner to represent maincategory and subCategory selection, once the user select the main category (first spinner) then change the second spinner to list the sub category in this main category . Both spinner list item have black color .

Hi , I am using updated version of this library .

Code: 

spMainCategory.setOnItemSelectedListener(new Spinner.OnItemSelectedListener() {
            @Override
            public void onItemSelected(Spinner parent, View view, int position, long id) {
                activityAdapter = new ArrayAdapter<String>(mContext, R.layout.spinner_item, GetActivityNames());
                activityAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
                spSubCategory.setAdapter(activityAdapter);
                activityAdapter.notifyDataSetChanged();
            }
        });

Problem :

After refresh second spinner adapter , all it's list item text color reset to white . but I want black text color on list item . There is any way to achieve it .

**Comment by enginebai** [comment]
@sushant015 what is your item layout `R.layout.spinner_item` in `ArrayAdapter`??
