### ISSUE TITLE
ProgressBar Color not working

### ISSUE THREAD

**Issue by dkartik** [rey5137/material#272]
Basic theme:
   
    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:textColorHint">@android:color/darker_gray</item>
        <item name="windowActionBar">false</item>
        <item name="colorAccent">@android:color/holo_blue_bright</item>
    </style>

Widget:

    <com.rey.material.widget.ProgressView
        android:id="@+id/wallet_progress_bar"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_gravity="center"
        app:pv_autostart="true"
        app:cpd_strokeColor="@android:color/holo_blue_bright"
        app:cpd_strokeSecondaryColor="@android:color/holo_red_dark"
        app:pv_circular="true"
        app:pv_progressStyle="@style/Material.Drawable.CircularProgress"
        app:pv_progressMode="indeterminate"/>

So, since my theme is light progress view is always picking up white color.
I want to use the progress view on the theme with no action bar.

Dependency:

    compile 'com.android.support:appcompat-v7:23.0.1'

**Comment by Prographer** [comment]
I have same issue, so I have style Inheritance.

```
<style name="CircularProgress" parent="Material.Drawable.CircularProgress">
       <item name="cpd_strokeColor">@color/accent</item>
</style>
```

```
<com.rey.material.widget.ProgressView xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/loading_spinner"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_centerInParent="true"
        app:pv_autostart="true"
        app:pv_circular="true"
        app:pv_progressMode="indeterminate"
        app:pv_progressStyle="@style/CircularProgress" />
```

**Comment by dkartik** [comment]
@Prographer Thanks :+1: 
This works :)
