### ISSUE TITLE
How to set the colored dot in the RadioButton?

### ISSUE THREAD

**Issue by rocboronat** [rey5137/material#28]
The wiki page explains how to set the tick color in the CheckBox, but don't explain how to set the dot color in the CheckBox: https://github.com/rey5137/Material/wiki/Switch

By the way, thanks for your work!

**Comment by rey5137** [comment]
The color of dot in RadioButton is same as stroke color, so you can set it via `rbd_strokeColor` attribute.

**Comment by rocboronat** [comment]
Oh! Then... how to set "the other" color? In your example, the Widget it's grey when unselected, and blue when selected. But there's only one attribute to set the color. If the attribute affects the radio when selected, how to set the color when unselected?

Thanks!

**Comment by rey5137** [comment]
The attribute can accept a ColorStateList value. You can create a custom selector XML yourself and set it to the attribute.

**Comment by rocboronat** [comment]
Great! Thank you, @rey5137
