### ISSUE TITLE
how can i get text inserted by user in EditText?

### ISSUE THREAD

**Issue by namikazebadri** [rey5137/material#283]
Hi, i have a confusing problem, here is my code to get the value of the EditText : 
EditText idOutlet = (EditText) findViewById(R.id.id_outlet);
String idOutlet = idOutlet.getText().toString();
but the value of idOutlet is empty, how is it?, how i can get the value of the EditText?,

**Comment by xdevs23** [comment]
Have you imported `com.rey.material.widget.EditText` instead of `android.widget`?

If you need both, use this code:
```java
com.rey.material.widget.EditText idOutlet = (com.rey.material.widget.EditText) findViewById(R.id.id_outlet);
String idOutletStr = idOutlet.getText().toString();
// do something with idOutletStr
```

Also note, that you cannot use the **same** variable name for both types.

Also you could try `idOutlet.getEditableText().toString()`, maybe this would return the correct value.
