### ISSUE TITLE
Thumb image

### ISSUE THREAD

**Issue by Grountex** [rey5137/material#286]
Hello,
 Is it possible to change the circle thumb on slider item with drawable? (or custom xml)
Thank you!

**Comment by rey5137** [comment]
You can only change the size or color of thumb. Please view [Slider](https://github.com/rey5137/material/wiki/Slider) for more details.

**Comment by e1631225** [comment]
Is there a way to set different colors for thumb and primaryColor.Now thumb and primarycolor is always same.
