### ISSUE TITLE
EditText  et_supportMaxChars

### ISSUE THREAD

**Issue by Jakevin** [rey5137/material#29]
Hi Rey
I come from Taiwan, Using Chinese.

In Chinese, one word = 2 byte

et_supportMaxChars is count EditText Length, not EditText.toString().getBytes()

How can i do when Use Chinese & English mix

**Comment by rey5137** [comment]
May be you should set `et_supportMaxChars` to `@integer/max_chars_value` and change the value based on language. For example in `values\integers.xml` file:
```xml
    <integer name="max_chars_value">10</integer>
```
And in `values-zh\integers.xml` file:
```xml
    <integer name="max_chars_value">20</integer>
```
