### ISSUE TITLE
Unable to start activity EditText error when ORIENTATION 

### ISSUE THREAD

**Issue by ArabAgile** [rey5137/material#290]
I'm getting this error when changing orientation of activity:

Unable to start activity ComponentInfo{ae.ac.hbmsu.sc/com.test.app.MyActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.TextView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/new_text. Make sure other views do not use the same id.

xml manifest:
`<activity
            android:name=".app.MyActivity"
            android:configChanges="orientation"
            android:screenOrientation="fullUser"
            android:windowSoftInputMode="adjustResize" >
        </activity>`

Any solution?

**Comment by ArabAgile** [comment]
solved when setting screenSize in configChanges
`android:configChanges="orientation|screenSize"`

**Comment by azizbekian** [comment]
What if I do not want set flags on my activity?
