### ISSUE TITLE
Can we use this library for API 23?

### ISSUE THREAD

**Issue by FastDr1v3r** [rey5137/material#301]
Unfortunately I'm not able to use an API 23 emulator on my pc (for some specs reasons) and I'm wondering if we can still use this library in API 23?

**Comment by azadso** [comment]
I have the same Issue, I hope him to response to the problem soon :+1:

**Comment by fernandodev** [comment]
@FastDr1v3r it was fixed in PR #299 
I'm waiting for merge

**Comment by michel-t-86** [comment]
yeah same problem here

**Comment by rey5137** [comment]
I have released 1.2.2 version that fixed this bug.
