### ISSUE TITLE
Does this requires AppCompat-v7:23.1.1?

### ISSUE THREAD

**Issue by praveenbroski** [rey5137/material#307]
Hi,
I have a doubt. Is this requires the latest appcompat version because I have appcompat-v7:22.2.0 only. When I tried to use your library it showed me to install appcompat-v7:23.1.1. I have slow internet connection only. I tried once to update SDK but failed after some progress. Please clarify me does this requires latest version of AppCompat?

**Comment by faraz20** [comment]
I have same problem

**Comment by praveenbroski** [comment]
Yes, It does requires to update the Support Library.
