### ISSUE TITLE
DatePicker scrolling issue

### ISSUE THREAD

**Issue by major-laslo** [rey5137/material#31]
If you open a datepicker provided by the library, and you click within the dialog but outside the number fields, when you try scroll the picker again it gets scrolled off screen instead of normal behavior. I attached two videos with visible touches, to illustrate it better.

https://youtu.be/UmH4QCUNZ7k

http://youtu.be/SoLKIO6sNFU

Reproduced on Nexus 5, 5.1

Could not reproduce on pre-lollipop devices.

**Comment by major-laslo** [comment]
The pull request I made contains a fix to this issue, and has been tested on a wide range of devices from ICS up to 5.0 and 5.1. Feel free to disregard the other changes which I had to make to be able to build without your signing keys.

**Comment by rey5137** [comment]
I added the fix to `dev` branch.
