### ISSUE TITLE
Cannot get property 'BINTRAY_USERNAME' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by Nopu70** [rey5137/material#328]
i used your demo in Android Studio, i get this error Error:"Cannot get property 'BINTRAY_USERNAME' on extra properties extension as it does not exist“ .Because I live in China?
what should i do,

**Comment by ModirGithub** [comment]
It is Very Easy:
Value of Variables====>
    bintrayUser ='BINTRAY_USERNAME'
    bintrayApiKey ='BINTRAY_APIKEY'
    bintrayGpgPassword = 'GPG_PASSWORD'

**Comment by androidlli** [comment]
thank you ,it is resolve my problem!

**Comment by paragones** [comment]
hello, where should I put these variables?

**Comment by ModirGithub** [comment]
Hi
go to this link , Please:
https://github.com/rey5137/material/blob/master/dist/bintray.gradle

**Comment by ModirGithub** [comment]
Hi:🌷
Open this page please:
https://github.com/rey5137/material/blob/master/dist/bintray.gradle

**Comment by paragones** [comment]
got it thanks!
