### ISSUE TITLE
set style programmatically

### ISSUE THREAD

**Issue by hrsalehi** [rey5137/material#339]
How ca I set style for my buttons programmatically? I have dynamic approach to generate some buttons but I don't know how to set my styles for these buttons.
for Android L and above ```Button``` constructor get a forth parameter as style but for other android version I don't know how!

For android L:
```java
Button button = new Button(PostDetailsActivity.this, null, 0, R.style.LightFlatColorButtonRippleStylePath);
```

**Comment by rey5137** [comment]
You can use `applyStyle(int)` method of `Button` class.
