### ISSUE TITLE
Dialog does not dismiss when I call dialog.dismiss() right after dialog.show()

### ISSUE THREAD

**Issue by Blue-Lan** [rey5137/material#340]
I found that if I call dialog.dismiss() right after(or for a very short time after) dialog.show(), the showing dialog will not dismiss, I have some code that determine whether user has connected to internet, if not connected, do http post, close the dialog and show Toast "No internet connection" otherwise.

**Comment by Blue-Lan** [comment]
I found that applying the animation "anim_scale_in.xml" on dialogs causes the problem, is there any solution to it?

**Comment by kainjinez** [comment]
Do you have any solution?
