### ISSUE TITLE
there is no background in bottomsheet

### ISSUE THREAD

**Issue by meeftah** [rey5137/material#345]
> private void showcountryBottomSheet(){
>         mBottomSheetDialog = new BottomSheetDialog(mActivity, R.style.Material_App_BottomSheetDialog);
>         View v = LayoutInflater.from(mActivity).inflate(R.layout.showcountry_activity, null);
>         ViewUtil.setBackground(v, new ThemeDrawable(R.array.bg_window));
>         mBottomSheetDialog.heightParam(ViewGroup.LayoutParams.MATCH_PARENT);
>         mBottomSheetDialog.contentView(v)
>                 .show();
>     }

no matter what I do, my bottomsheet has no background...any help?

**Comment by lixp185** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
