### ISSUE TITLE
Setting Content of custom dialog Textview

### ISSUE THREAD

**Issue by tatlacas** [rey5137/material#35]
How do i set text for components inside a custom dialog layout, or get entered text from edittext elements within the custom dialog

**Comment by rey5137** [comment]
to get a view in your custom content view, you can use `findViewById(int)` method of `Dialog` class.

**Comment by pavanjaju** [comment]
findViewById is always returning null. There is no visible way to access them :(

**Comment by rey5137** [comment]
Please give more details about your case, like the code and xml you used.
