### ISSUE TITLE
edittext.setError shows "null,errormessage"

### ISSUE THREAD

**Issue by paragones** [rey5137/material#371]
I am working on Android IceCream. I noticed that edittext.setError shows "null,errormessage". 
Am I doing something wrong here?

Here's the code. 

```
 if (commentEditText.getText().toString().isEmpty())
                    commentEditText.setError("Please Write a Comment");
```

**Comment by rey5137** [comment]
Seem like your EditTest has `et_supportMode` attribute set to `helperWithError` . You should change it to `helper`

**Comment by paragones** [comment]
Got it! Will check! Thanks!
