### ISSUE TITLE
Determinate progress view issue

### ISSUE THREAD

**Issue by AlekseiPecherei** [rey5137/material#376]
Hello.
Thank you for beautiful library.
I've a question. 
I'm using determinate ProgressView in my test project.

```
    <com.rey.material.widget.ProgressView
        android:id="@+id/progress"
        android:layout_width="87dp"
        android:layout_height="87dp"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:layout_gravity="center"
        app:pv_autostart="false"
        app:pv_circular="true"
        app:pv_progressMode="determinate"
        app:pv_progressStyle="@style/CircularProgressOrange" />

<style name="CircularProgressOrange" parent="Material.Drawable.CircularProgress">
    <item name="cpd_strokeColor">@color/text_orange</item>
    <item name="cpd_initialAngle">270</item>
</style>
```

The main problem that progressview has a strange behaviour.
It fills like determinate progress and rotate as indeterminate progress.
Can you help me?
![device-2016-05-25-152318](https://cloud.githubusercontent.com/assets/3646963/15539753/e84a48b6-228c-11e6-8697-deb516f81f9c.png)
![device-2016-05-25-152334](https://cloud.githubusercontent.com/assets/3646963/15539754/e84d917e-228c-11e6-8344-bb2c26682311.png)
![device-2016-05-25-152346](https://cloud.githubusercontent.com/assets/3646963/15539755/e85346be-228c-11e6-8b9d-e45b06e5e7f2.png)

**Comment by okacat** [comment]
Late answer, but might help someone - try setting the `cpd_rotateDuration="-1"`.

**Comment by AlekseiPecherei** [comment]
Thanks

**Comment by Ramuhyderabad** [comment]
how to change color every rotation
