### ISSUE TITLE
Proper documentation (Javadoc)

### ISSUE THREAD

**Issue by kanytu** [rey5137/material#38]
There is no documentation for listeners for people who add the library from maven:

Example:
![image](https://cloud.githubusercontent.com/assets/560921/7070853/8ee64c04-ded9-11e4-8b1a-7284ec774e5f.png)

I had to check the code on the repo to see what they really mean.

**Comment by rey5137** [comment]
I have release `1.1.1` version that added javadoc for all widgets.
