### ISSUE TITLE
Gradle could not found library

### ISSUE THREAD

**Issue by joielechong** [rey5137/material#380]
Gradle can't found library with:
`compile 'com.github.rey5137:material:1.2.3`

But it works with:
`compile 'com.github.rey5137:material:1.2.3@aar'`

**Comment by rey5137** [comment]
There are some errors when I submit `1.2.3` version to Jcenter. I have published `1.2.4` version that fix this bug. You can use `compile 'com.github.rey5137:material:1.2.4` now.

**Comment by joielechong** [comment]
Great... Thank You...:D
