### ISSUE TITLE
Library version is not updating

### ISSUE THREAD

**Issue by DearDhruv** [rey5137/material#386]
Hello @rey5137 

I see that you have updated library few days ago.
But I don't get update in Android Studio. Current version is 1.3.4 on GITHUB.
I think it is due to this line in [distInfo.gradle](https://github.com/rey5137/material/blob/master/dist/distInfo.gradle#L16)

Let me know any update.
Thanks.

**Comment by rey5137** [comment]
The latest version is 1.2.4. There's a typo in commit message.

**Comment by DearDhruv** [comment]
ohh, ok.
But your commit release says 1.3.4. :(
