### ISSUE TITLE
Slider min and max  value

### ISSUE THREAD

**Issue by madart** [rey5137/material#40]
Hi, I'm have a problem with Slider. Why min and max  values , not possible change from code? I have two sliders on the view, and them min a max values is interrelated.

**Comment by rey5137** [comment]
I will added it on next version. And you're welcome to make pull request to `dev` branch.

**Comment by madart** [comment]
It's great! Thank you for the lib!

**Comment by itekk** [comment]
Is this feature implemented??

**Comment by Vivalemuc** [comment]
I am interested too. When this feature will be available ?

**Comment by rey5137** [comment]
This feature is added to `1.1.1-SNAPSHOT` version. You can change the min and max value via ` setValueRange(int min, int max, boolean animation)` method.

**Comment by Vivalemuc** [comment]
When the version 1.1.1 will be released ?
