### ISSUE TITLE
determine Progress Not working

### ISSUE THREAD

**Issue by starsoheil2007** [rey5137/material#441]
Hi
Thanks for your library but when i use determine circular ProgressView not show progress .
My code is :
`                <com.rey.material.widget.ProgressView
                    android:id="@+id/downloadProgress"
                    style="@style/LightDeterminateInCircularProgressView"
                    android:layout_width="38dp"
                    android:layout_height="38dp"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center" />` 

` <style name="LightDeterminateCircularProgressView">
        <item name="pv_autostart">false</item>
        <item name="pv_circular">true</item>
        <item name="pv_progressStyle">@style/LightDeterminateCircularProgressDrawable</item>
        <item name="pv_progressMode">determinate</item>
    </style>

    <style name="LightDeterminateInCircularProgressView" parent="LightDeterminateCircularProgressView">
        <item name="pv_progressStyle">@style/LightDeterminateInCircularProgressDrawable</item>
    </style>

    <style name="LightDeterminateCircularProgressDrawable" parent="Material.Drawable.CircularProgress.Determinate">
        <item name="cpd_strokeColor">@color/colorPrimary</item>
        <item name="cpd_inAnimDuration">0</item>
        <item name="cpd_outAnimDuration">0</item>
        <item name="cpd_initialAngle">-90</item>
    </style>

    <style name="LightDeterminateInCircularProgressDrawable" parent="LightDeterminateCircularProgressDrawable">
        <item name="cpd_inAnimDuration">400</item>
        <item name="cpd_outAnimDuration">400</item>
    </style>`

`
            vh.downloadProgress = (ProgressView) convertView.findViewById(R.id.downloadProgress);
vh.downloadView.setVisibility(View.VISIBLE);
                vh.downloadProgress.setProgress(0f);
                vh.downloadProgress.start();
                vh.downloadProgress.setProgress(vh.downloadProgress.getProgress() + 0.5f);
`

Please help me to resolve this issue, thanks

**Comment by Sunnatilla** [comment]
@starsoheil2007 How did you resolve this problem ? When I use determine mode also progressbar is not showing
