### ISSUE TITLE
Click in empty space of DatePicker distorts its display

### ISSUE THREAD

**Issue by Loscillo** [rey5137/material#45]
Hi,

I don't know if it is the same bug of #12. When I use DatePicker, if I click on day or button, it's work, but when I click in empty space (no day, divider or just a next to the buttons), it has a strange behavior : ![screenshot_2015-04-13-17-09-51](https://cloud.githubusercontent.com/assets/1565272/7118622/bd67e4c8-e200-11e4-80d0-ec71a6c02211.png)

I use this code : 

```java
DatePickerDialog.Builder builder = new DatePickerDialog.Builder(
    R.style.DatePicker,
    current.getDayOfMonth(),
    current.getMonthOfYear() - 1,
    current.getYear(),
    1,
    0,
    current.getYear() + 2,
    value.getDayOfMonth(),
    value.getMonthOfYear() - 1,
    value.getYear()) {

    @Override
    public void onPositiveActionClicked(DialogFragment fragment) {
        DatePickerDialog picker = ((DatePickerDialog) fragment.getDialog());
        value = new DateTime(picker.getYear(), picker.getMonth() + 1, picker.getDay(), value.getHourOfDay(), value.getMinuteOfHour());
        textView.setText(value.toString(DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss")));
        super.onPositiveActionClicked(fragment);
    }

    @Override
    public void onNegativeActionClicked(DialogFragment fragment) {
        super.onNegativeActionClicked(fragment);
    }

};

builder.positiveAction("Valider");
builder.negativeAction("Annuler");

DialogFragment.newInstance(builder).show(manager, null);
```

And my style for this DatePicker : 

```xml
<style name="DatePicker" parent="Material.Widget.DatePicker">
    <item name="di_negativeActionTextColor">@color/material_blue</item>
    <item name="di_positiveActionTextColor">@color/material_blue</item>
    <item name="dp_selectionColor">@color/material_blue</item>
    <item name="di_backgroundColor">@color/material_grey</item>
    <item name="dp_headerSecondaryColor">@color/material_dark_blue</item>
</style>
```
I use the latest version of the library (1.1.0) and my phone is a One Plus One.

I hope you can help me,

Have a nice day

**Comment by rey5137** [comment]
It's a known bug #31 and already fixed in `dev` branch.

**Comment by anupsarode** [comment]
Hi Rey,

I'm experiencing the same issue. How do I use the fixed code?

Currently, I am using this in gradle build - compile 'com.github.rey5137:material:1.1.0'

Thanks!

**Comment by rey5137** [comment]
@anupsarode Please change to `1.1.1` version and check if the bug is fixed.

**Comment by anupsarode** [comment]
@rey5137 - Changed to 1.1.1 and got this error in styles.xml

   <style name="FloatingActionButton" parent="Material.Drawable.Ripple.Touch.Light">
        <item name="fab_backgroundColor">#FFDFDFDF</item>
        <item name="fab_elevation">4dp</item>
        <item name="fab_iconLineMorphing">@style/FloatingActionButtonIcon.Light</item>
        <item name="rd_delayClick">false</item>
    </style>

Boolean types not allowed at ('rd_delayClick' with value false)

**Comment by anupsarode** [comment]
@rey5137 - Removed the styles that I din't require and was able to compile the project. Seems like the bug is fixed. Thanks a ton :)

**Comment by rey5137** [comment]
`rd_delayClick` is changed to integer attribute on `1.1.1` version. You can check the Wiki for more details.
