### ISSUE TITLE
Spinner and DatePicker causing crash when targeting app to targetSdkVersion 27

### ISSUE THREAD

**Issue by shaikansaar** [rey5137/material#452]
Hi,

Since Android Oreo is the latest version now, I recently updated my app to target API 27 with below changes:

compileSdkVersion 27
    buildToolsVersion '27.0.2'
    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 27

Also updated the dependencies:

compile 'com.android.support:appcompat-v7:27.1.1'
    compile 'com.android.support:palette-v7:27.1.1'
    compile 'com.android.support:cardview-v7:27.1.1'
    compile 'com.android.support:recyclerview-v7:27.1.1'
    compile 'com.android.support:design:27.1.1'
    compile 'com.android.support:animated-vector-drawable:27.1.1'
    compile 'com.android.support:support-v13:27.1.1'

I am using the library version 1.2.2
compile 'com.github.rey5137:material:1.2.2'

I get errors in the app at runtime when accessig datepicker or spinner. Below is the error:

E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.ListViewCompat" on path: DexPathList[[zip file 

@rey5137 can you please provide a fix for this issue?

Regards,
Shaik

**Comment by hrsalehi** [comment]
same here

**Comment by anggrayudi** [comment]
Lazy @rey5137 wont give it updates. I am not sure that he is still alive.

**Comment by omidfaraji** [comment]
same for me.
@rey5137  please care about it

**Comment by mrnorouzi** [comment]
There was a problem in adding appCompat 27.1.x. The ListViewCompat class seems to be removed from this version of appCompat. I added this again into project and I tested it. It was fixed.
I think it will be good temporary solution.

**Comment by rey5137** [comment]
I already published new version 1.2.5 that fixed this issue. Pls check out. Sorry guys that I don't have much time to maintain this library.

**Comment by omidfaraji** [comment]
@rey5137 
good job. thanks.
just i can't sync gradle when i changed to version 1.2.5

the error is :
**Failed to resolve: com.github.rey5137:material:1.2.5**

**Comment by anggrayudi** [comment]
I just moved to this library, which is maintained very well:
https://github.com/wdullaer/MaterialDateTimePicker
