### ISSUE TITLE
Shadow in Button

### ISSUE THREAD

**Issue by patelakshay13890** [rey5137/material#46]
How can i apply Shadow like Z-scale in your Button ???
![rectangle_button](https://cloud.githubusercontent.com/assets/6092323/7131797/dccee7c6-e2a0-11e4-9cf6-27aa033b4d66.png)

**Comment by rey5137** [comment]
Currently `Button` doesn't support dynamic shadow. You should use a 9 patch drawable as your button's background.

**Comment by patelakshay13890** [comment]
through Code we cannot have these Effect ???

**Comment by patelakshay13890** [comment]
If I have 30 different Coloured Buttons , then it will become tedious
task...

**Comment by patelakshay13890** [comment]
Waiting for positive response..!!

**Comment by rey5137** [comment]
If you want to create a shadow colored button through code, you can create a custom drawable that draw solid color and shadow yourself, then set it as button's background via `setBackground(Drawable)` method.

**Comment by patelakshay13890** [comment]
Since I want backward compatibility , so we can't do this Shadow effect in
this lib project itself ??
