### ISSUE TITLE
Failed to resolve with version 1.3.0

### ISSUE THREAD

**Issue by zknabdi** [rey5137/material#469]
I am getting this error message 
ERROR: Failed to resolve: com.github.rey5137:material:1.3.0

Could please help

**Comment by zknabdi** [comment]
I resolved the issue by going back to the older version ( 'com.github.rey5137:material:1.2.5')

**Comment by mehdi7e** [comment]
@zknabdi 
it's bad idea...
how to resolve this problem

@rey5137

**Comment by mwillis72** [comment]
> I am getting this error message
> ERROR: Failed to resolve: com.github.rey5137:material:1.3.0
> 
> Could please help

Solved by going back to older version.
