### ISSUE TITLE
spinner rtl support

### ISSUE THREAD

**Issue by amorenew** [rey5137/material#47]
i want to use spinner in arabic
it's need arrow to to be in left and items gravity to right

**Comment by rey5137** [comment]
I have release `1.1.1` version. Now `Spinner` class support RTL layout. Can you please test it?

**Comment by amorenew** [comment]
i tried it but i can't see any difference
i fixed it in my fork

**Comment by rey5137** [comment]
Can you post the xml you used? Did you add `android:supportsRtl="true"` to `application` in AndroidManifest.xml ?

**Comment by amorenew** [comment]
no i didn't add it i just changed the device language but i will test it again

**Comment by amorenew** [comment]
i used your demo 
and android:supportsRtl="true" is exist in your manifest
still the same

**Comment by rey5137** [comment]
Which Android device you used? Android added full native support for RTL layouts from 4.2.

**Comment by amorenew** [comment]
yes i know all test in android 4.1 no rtl support
i tried it now on 4.4.4 note 3
spinner is rtl only text gravity should be right
in my fork it's work even in android 4.1

**Comment by rey5137** [comment]
The Spinner doesn't apply the layout direction to selected view, it's set by the layout you used. In my demo app, I forgot to add `android:textDirection="locale"` to item's layout.

**Comment by amorenew** [comment]
yes i got it

**Comment by amorenew** [comment]
but i will use my fork because my min sdk 14
good work .
