### ISSUE TITLE
neutralActionClickListener not set in DialogFragment

### ISSUE THREAD

**Issue by RayJJ** [rey5137/material#53]
negativeActionClickListener(mActionListener) is invoked twice, as below:

    @NonNull
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        com.rey.material.app.Dialog dialog = mBuilder == null ? new Dialog(getActivity()) : mBuilder.build(getActivity());
        dialog.positiveActionClickListener(mActionListener)
                .negativeActionClickListener(mActionListener)
                .negativeActionClickListener(mActionListener);
        return dialog;
    }

**Comment by rey5137** [comment]
I don't understand your point here. If you want to set click listener for neutral action, you can call `neutralActionClickListener(View.OnClickListener)` method.

**Comment by RayJJ** [comment]
That interface is usable for subclasses of Dialog but is not exposed directly by DialogFragment which wraps a builder containing the client listener code.

DialogFragment only links the negative and positive listeners in onCreateDialog() as follows:

    dialog.positiveActionClickListener(mActionListener)
            .negativeActionClickListener(mActionListener) 
            .negativeActionClickListener(mActionListener); /* <<<=== duplicate method call */

It looks like one of the duplicates should be a call to .neutralActionClickListener(mActionListener).

I have subclassed the material DialogFragment as a workaround, but it would be great if you could fix the library version.

Excellent library btw :-)

**Comment by rey5137** [comment]
Ok, I understand now. Thanks, I have pushed a fix to `dev` branch.

**Comment by RayJJ** [comment]
That's great, thanks.
