### ISSUE TITLE
[slider bug] It can not drag to the max value

### ISSUE THREAD

**Issue by tianqiujie** [rey5137/material#55]
<com.rey.material.widget.Slider
                        style="@style/Material.Widget.Slider.Discrete"
                        android:id="@+id/change_dialog_pitch"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:paddingLeft="10dp"
                        android:paddingRight="10dp"
                        app:sl_stepValue="1"
                        app:sl_maxValue="100"
                        app:sl_minValue="-100"
                        app:sl_value="100"
                        app:sl_primaryColor="@color/seekBar"
                        app:sl_secondaryColor="@color/seekBar"
                        />

**Comment by tianqiujie** [comment]
It only can drag to the 0 value.

**Comment by rey5137** [comment]
I have added a fix to next version.
