### ISSUE TITLE
Inflating Error in XML!

### ISSUE THREAD

**Issue by IRMobydick** [rey5137/material#56]
I get this error when I want use your library in eclipse:

`04-17 03:53:39.139: E/AndroidRuntime(13742): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.may3am.video/com.may3am.video.MainActivity}: android.view.InflateException: Binary XML file line #28: Error inflating class com.rey.material.widget.ProgressView
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2394)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.ActivityThread.access$900(ActivityThread.java:172)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.os.Looper.loop(Looper.java:136)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.ActivityThread.main(ActivityThread.java:5586)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at java.lang.reflect.Method.invoke(Method.java:515)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at dalvik.system.NativeStart.main(Native Method)
04-17 03:53:39.139: E/AndroidRuntime(13742): Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class com.rey.material.widget.ProgressView
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:350)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.Activity.setContentView(Activity.java:2031)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.may3am.video.MainActivity.onCreate(MainActivity.java:94)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.Activity.performCreate(Activity.java:5451)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	... 11 more
04-17 03:53:39.139: E/AndroidRuntime(13742): Caused by: java.lang.reflect.InvocationTargetException
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at java.lang.reflect.Constructor.constructNative(Native Method)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.view.LayoutInflater.createView(LayoutInflater.java:600)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	... 24 more
04-17 03:53:39.139: E/AndroidRuntime(13742): Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at android.content.res.TypedArray.getColor(TypedArray.java:327)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.rey.material.drawable.CircularProgressDrawable$Builder.<init>(CircularProgressDrawable.java:550)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.rey.material.drawable.CircularProgressDrawable$Builder.<init>(CircularProgressDrawable.java:536)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.rey.material.widget.ProgressView.applyStyle(ProgressView.java:70)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.rey.material.widget.ProgressView.init(ProgressView.java:51)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.rey.material.widget.ProgressView.<init>(ProgressView.java:47)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	at com.rey.material.widget.ProgressView.<init>(ProgressView.java:35)
04-17 03:53:39.139: E/AndroidRuntime(13742): 	... 27 more`

**Comment by mehrad-rafigh** [comment]
Would be really helpful if you would attach your xml and code in order to solve your problem
