### ISSUE TITLE
CheckBox in ListView always displayed in black

### ISSUE THREAD

**Issue by draco1023** [rey5137/material#61]
![image](https://cloud.githubusercontent.com/assets/1821583/7219387/96fb1aa2-e6cf-11e4-8f87-2bfd6606f293.png)

colors.xml
`<resources>
    <color name="primary">#2196F3</color>
    <color name="primary_dark">#1976D2</color>
    <color name="primary_light">#BBDEFB</color>
    <color name="accent">#4CAF50</color>
    <color name="primary_text">#212121</color>
    <color name="secondary_text">#727272</color>
    <color name="icons">#FFFFFF</color>
    <color name="divider">#B6B6B6</color>
</resources>`

styles.xml
`<resources>
    <style name="AppTheme" parent="AppTheme.Base">
    </style>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>

        <item name="android:textColorPrimary">@color/primary_text</item>
        <item name="android:textColorSecondary">@color/secondary_text</item>
    </style>
</resources>`

PS 1. It displays in the right way out of ListView.
      2. Custom style would not work either

**Comment by rey5137** [comment]
Can you post your layout xml of child view, and the adapter code? And the default style of CheckBoxDrawable use `colorControlNormal` and `colorControlActivated` attributes of AppCompat theme.

**Comment by draco1023** [comment]
I've tried colorControlNormal and colorControlActivated attributes, but nothing happened.
Here is my code.

item_child.xml

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="match_parent">
    <com.rey.material.widget.CheckBox
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/radio_device"/>
    <TextView
        android:layout_width="0dp"
        android:layout_weight="1"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"
        android:gravity="center_vertical"
        android:textColor="@color/primary_text"
        android:id="@+id/text_device_name"/>
    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/image_device_flag"
        android:layout_gravity="center_vertical"
        android:src="@drawable/ic_action_chevron_right"/>
</LinearLayout>`

Adapter.java

`public View getView(int i, View view, final ViewGroup viewGroup) {
        final ViewHolder viewHolder;
        if (view == null) {
            view = MyApp.getLayoutInflater().inflate(R.layout.item_child, null);
            viewHolder = new ViewHolder(view);
            view.setTag(viewHolder);
        } else {
            viewHolder = (ViewHolder) view.getTag();
        }`

        final ListView list = (ListView)viewGroup;
        final Device device = devices.get(i);

        viewHolder.checkedView.setChecked(device.isChecked());
        viewHolder.checkedView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                // ...
            }
        });
        viewHolder.nameView.setText(device.getName());
        viewHolder.flagView.setVisibility(device.isLeaf() ? View.INVISIBLE : View.VISIBLE);

        return view;
    }`

In my adapter, I use a global layoutinflater and null as root view to inflate the child view, does it matter?

**Comment by rey5137** [comment]
First, please add `style=@style/Material.Drawable.CheckBox` to CheckBox in item_child.xml so your CheckBox can use default style.
Second, what is your global LayoutInflater? May be you should use this code instead:
```java
view = LayoutInfater.from(viewGroup.getContext()).inflate(R.layout.item_child, viewGroup, false);
```

**Comment by draco1023** [comment]
Thanks!
The second one fixed my problem. The style attribute is unnecessary.
I used `(LayoutInflater) getSystemService(LAYOUT_INFLATER_SERVICE)` in my Application class as global LayoutInflater. So it is not that convenient.

**Comment by rey5137** [comment]
Yes, the style isn't necessary, but it's recommended.
`ApplicationContext ` don't set theme by default. If you want to use it, here is a [solution](http://stackoverflow.com/questions/2118251/theme-style-is-not-applied-when-inflater-used-with-applicationcontext)
