### ISSUE TITLE
arabic rtl support

### ISSUE THREAD

**Issue by amorenew** [rey5137/material#62]
my android team work on Arabic rtl support to your library
we have finished calendar to support Arabic
in this fork
https://github.com/amorenew/material
i need to rotate days name so it appear good in arabic but i can't 
use canvas.rotate to make what i want
![calendar1](https://cloud.githubusercontent.com/assets/2842459/7219621/3d64841e-e6a8-11e4-807b-a611607ff448.png)
in tablet calendar dialog is very big and font is small i think it should be smaller than this
![calendar2](https://cloud.githubusercontent.com/assets/2842459/7219622/3d69a688-e6a8-11e4-899d-1bbe437b1cf9.png)
also i working on spinner rtl which i post at this link
https://github.com/rey5137/material/issues/47

**Comment by amorenew** [comment]
i made class for locale set called LocalUtil

**Comment by DHuckaby** [comment]
@amorenew Do you know if your team will be working on the TabPageIndicator also? I have found it doesn't work as expected.

**Comment by amorenew** [comment]
i am not sure about tabs may we use this library tab or another one i have

https://github.com/neokree/MaterialTabs
https://github.com/chenupt/SpringIndicator
https://github.com/ogaclejapan/SmartTabLayout

what is not work as expected exactly ?

**Comment by DHuckaby** [comment]
I use the tab indicator included in this library, ref: https://github.com/rey5137/Material/wiki/TabPageIndicator

The issue I see is the tabs are out of order and the accent line acts erratically.

**Comment by amorenew** [comment]
i don't know a lot about animation but i think it's the default android

**Comment by rey5137** [comment]
I have release `1.1.1` version. Now `DatePickerDialog` class support RTL layout. Can you please test it?

**Comment by amorenew** [comment]
i test it on emulator android 4.1 genymotion tablet 10 inch
Cancel and OK buttons not translated and the dialog is very big i fixed it in my fork
in emulator android 4.1 genymotion days number not in arabic .
in real device samsuang galaxy S2 android 4.1 not translated

in my fork i solved 
1-small dialog in tablet.
2-arabic string for day's names and month's names for non support rtl android versions.
3-method to convert english numbers to arabic numbers.
4-string for ok and cancel buttons.
5-font size bigger in tablet dialog.

thanks
