### ISSUE TITLE
How to use attributes 

### ISSUE THREAD

**Issue by d7coders** [rey5137/material#65]
hi , I'm trying to change the radio button color using rbd_strokeColor but nothing changed, can you explain how to do it with an example?
Thanks

**Comment by rey5137** [comment]
Can you post your current xml?

**Comment by d7coders** [comment]
<com.rey.material.widget.RadioButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="New RadioButton"
        rbd_strokeColor="#FFCC0000"
        android:id="@+id/radioButton"
        android:layout_alignParentTop="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true" />

**Comment by rey5137** [comment]
You have to declare a custom namespace in the root view of your layout:
```xml
xmlns:app="http://schemas.android.com/apk/res-auto"
```
Then use it in RadioButton:
```xml
app:rbd_strokeColor="#FFCC0000"
```

**Comment by d7coders** [comment]
Thanks :) , this works
