### ISSUE TITLE
delayClick is always true

### ISSUE THREAD

**Issue by Digmaster** [rey5137/material#68]
Despite my best efforts (settings rd_delayClick=false) onClick is only every fired when the animation has completed. Used on a Button.

**Comment by rey5137** [comment]
Can you post your xml?

**Comment by Digmaster** [comment]
Of course.
My style:
    <style name="FlatWaveColorButtonRippleStyle" parent="Material.Drawable.Ripple.Wave.Light">
        <item name="android:background">@null</item>
        <item name="rd_rippleColor">@color/primary</item>
        <item name="rd_cornerRadius">4dp</item>
        <item name="rd_delayClick">false</item>
    </style>
Layout:
        <com.rey.material.widget.Button
            android:layout_width="wrap_content"
            android:layout_height="@dimen/bt_height"
            android:text="Delete"
            android:id="@+id/deleteButton"
            android:layout_marginLeft="16dp"
            android:visibility="gone"
            android:textColor="@color/accent"
            app:rd_enable="true"
            app:rd_delayClick="false"
            style="@style/FlatWaveColorButtonRippleStyle"
            />

**Comment by thomas76** [comment]
Just for info, it seems fixed in the dev branche since commit d44ffd4

**Comment by rey5137** [comment]
I have released `1.1.1` version. Now `rd_delayClick` is a integer attribute. Please view [Button](https://github.com/rey5137/material/wiki/Button) page for more details.
