### ISSUE TITLE
TimePickerDialog set attribute

### ISSUE THREAD

**Issue by pask23** [rey5137/material#71]
How can use attribute tp_24Hour for change format. I doesn't understand, can you show me a example?thanks

**Comment by rey5137** [comment]
Currently TimePickerDialog auto set 24Hour mode for TimePicker view depend on default time format the system use. You can only apply `tp_24Hour` attribute if you use TimePicker view directly.

**Comment by pask23** [comment]
My system use time format 24Hour, but TimePickerDialog show 12h(am, pm) mode. Where I mistake?
I try your demo app but is same, it's show 12Hour mode

**Comment by rey5137** [comment]
There is a bug in checking the default system format. I will fix it in next version and make `TimePickerDialog` support `tp_24Hour` attribute.
