### ISSUE TITLE
can't use getSelectedItem() in spinner

### ISSUE THREAD

**Issue by d7coders** [rey5137/material#72]
Hi, 

this is my code

    import com.rey.material.widget.Spinner;
    ...

    Spinner spin = (Spinner)findViewById(R.id.spinner1);
    String st = spin.getSelectedItem().toString();

I got " cannot resolve getSelectedItem() method"  error

thanks

**Comment by rey5137** [comment]
I will add `getSelectedItem()` method in next version.
