### ISSUE TITLE
Example for customizing Switch

### ISSUE THREAD

**Issue by tryme34** [rey5137/material#73]
Is there any example of how can I customize the Switch (change color, change size etc) either programmatically or via XML? I tried customizing via XML but it didn't work, so I am propably missing something.

**Comment by rey5137** [comment]
Can you please post your xml?

**Comment by 1hsyn1** [comment]
hi there, you have a great library and neat wiki. Thank you for your work, but wiki could be better. I am using below code for styling switch everything works, but there are couple of problems.  The track does not have curved corners like in this page https://github.com/rey5137/material/wiki/Switch .
And I could not find how to set different color in different states to color of track and thumb 

    <style name="settings_switch" parent="settings">
        <item name="sw_thumbColor">#ff0000</item>
        <item name="sw_trackSize">15dp</item>
        <item name="sw_trackCap">5000</item>
        <item name="sw_thumbRadius">10dp</item>
        <item name="sw_thumbElevation">3dp</item>
    </style>

**Comment by rey5137** [comment]
There're 3 available value for `sw_trackCap` attribute: **BUTT**, **ROUND** and **SQUARE** (I have updated Wiki). And `sw_thumbColor`, `sw_trackColor` attribute can accept a ColorStateList resource.

**Comment by rey5137** [comment]
There're 3 available value for `sw_trackCap` attribute: **BUTT**, **ROUND** and **SQUARE** (I have updated Wiki). And `sw_thumbColor`, `sw_trackColor` attribute can accept a ColorStateList resource.

**Comment by rey5137** [comment]
There're 3 available value for `sw_trackCap` attribute: **BUTT**, **ROUND** and **SQUARE** (I have updated Wiki). And `sw_thumbColor`, `sw_trackColor` attribute can accept a ColorStateList resource.

**Comment by 1hsyn1** [comment]
the ColorStateList, I should have think that. Thanks for your help
