### ISSUE TITLE
Can't checkout

### ISSUE THREAD

**Issue by humazed** [rey5137/material#77]
When I try to checkout the project it gives me that error.

```java
Error:(17, 0) Could not find property 'MATERIAL_KEYSTORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.
```

what should I do?

**Comment by rey5137** [comment]
You can comment out *signingConfigs* part in build.gradle setting of app module.

**Comment by humazed** [comment]
that's works very well, I know it must be obvious but I pretty new to Gradle.
thanks for the help and for your amazing library.

**Comment by jbxkuang** [comment]
可以把这一段注释掉

**Comment by anonymousventures** [comment]
Hi I get "Error:(28, 0) Could not find property 'release' on SigningConfig container."

Could you let me know how to fix? thanks!

**Comment by Morgan-Leon** [comment]
Comment out
