### ISSUE TITLE
No 24/hr schema input support in TimePicker

### ISSUE THREAD

**Issue by inteist** [rey5137/material#80]
I am talking about this:
![tp-24hr](https://cloud.githubusercontent.com/assets/53954/7438791/5ff0037a-f038-11e4-82ac-e4e117f34463.png)

the widget seems to convert everything into 12hr format and runs exclusively in 12hr format.

Am I missing something? More than half the world uses the 24/hr schema.

**Comment by rey5137** [comment]
`TimePicker` widget support 24 hour mode via `tp_24Hour` attribute, but `TimePickerDialog` currently manually set it to default system format. In next version, I will make `TimePickerDialog` support `tp_24Hour` attribute.

**Comment by inteist** [comment]
Rey, the thing is:

"TimePickerDialog currently manually set it to default system format"

this is not true. It is not working. With 24hr format in the settings the dialog still has 12hr format.

**Comment by rey5137** [comment]
Yes. There is a bug in checking default system format. I will fixed it in
next version.

**Comment by inteist** [comment]
Thank you. Can you please fix it asap, should be an easy fix.

Please also check out the pull request I sent that fixes the formatting for the 12hr. I checked it and it seems to work fine.

**Comment by inteist** [comment]
Oh, looks like you already fixed it in f65c0cb9b0807fb240faa4867bbc34f3c2d081af

Thanks!
