### ISSUE TITLE
Leading zero in 12/hr format in the TimePicker

### ISSUE THREAD

**Issue by inteist** [rey5137/material#81]
12hr format should NOT have a leading zero.  I got it fixed and will be submitting a fix via pull for this. Please review merge.

**Comment by rey5137** [comment]
I prefer leading zero because it feel more balance. But I'll add a new attribute for TimePickerDialog to indicate using leading zero format or not.

**Comment by inteist** [comment]
Just FYI: the default should be "false" because this is how it is supposed to be by the **convention**, regardless of how it looks. This is how people know and use it.

**Comment by rey5137** [comment]
I have released `1.1.1` version. You can use `tp_leadingZero` attribute now (default value is false).
