### ISSUE TITLE
Set padding for the internal mInputView in EditText

### ISSUE THREAD

**Issue by Android-s14** [rey5137/material#83]
As far as I understand, currently it's impossible to set padding for the underlying `android.widget.EditText` in `com.rey.material.widget.EditText`. Would be great to have this opportunity, at least programmatically, through setter.

**Comment by rey5137** [comment]
You can set the viewId of internal input view via `et_inputId` attribute then retrieve the view via `findViewById(int)` method. After that you can set the padding of it as you want (but use it with caution because it can mess up the alignment of `com.rey.material.widget.EditText`)

**Comment by Android-s14** [comment]
Thanks, makes sense.
