### ISSUE TITLE
No resource found that matches the given name

### ISSUE THREAD

**Issue by sparrowu93** [rey5137/material#84]
Hey,there.
I am trying to assemble this powerful library to my app,but it turns out a little puzzle on me.

I got "No resource found that matches the given name" error,I searched for that and google throw some answer on "sdk/support library/api  version" back to me,but I believe it is not correct on this problem.

 (at 'pv_progressStyle' with value '@style/ColorsCircularProgressDrawableStyle').
Error:(57, 39) No resource found that matches the given name (at 'pv_progressStyle' with value '@style/ColorsCircularProgressDrawableStyle').
/app/src/main/res/layout/listfooter_more.xml
Error:(27, 31) No resource found that matches the given name (at 'pv_progressStyle' with value '@style/ColorsCircularProgressDrawableStyle').
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1

I get confused on it,hope some tips of you.

**Comment by phamvansy** [comment]
Creaded attrs.xml file in values folder
