### ISSUE TITLE
Show Progores Dialog ?

### ISSUE THREAD

**Issue by patelakshay13890** [rey5137/material#85]
How can we see Progress Dialog with Title & Message not intermediate progressbar

**Comment by rey5137** [comment]
You can use SimpleDialog and set custom layout (contains a TextView and ProgressView) via `contentView(int)` method

**Comment by anupsarode** [comment]
I have added a custom layout to the dilaog that contains the progress view and it works fine. Now while the undeterminate progress view is being shown, if the user touchs the back button, the dialog is dismissed. Is there any way if I can get a dialog dismissed callback? or any way no to dismiss the dialog on back button press?

**Comment by rey5137** [comment]
`com.rey.material.app.Dialog` is extended from `android.app.Dialog` so you can call `setOnDismissListener()` to listen to dismissed event, and call `setCancelable(false)` to make dialog not dismiss when press BACK button.
