### ISSUE TITLE
hi, Can you make a code for RippleLayout?

### ISSUE THREAD

**Issue by Dengzer** [rey5137/material#86]
like this:
 < RippleLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:gravity="center_horizontal"
                android:orientation="vertical"  >
                < TextView
                    style="@style/item_textview"
                    android:text="小学课程" / >
 < /RippleLayout >

**Comment by rey5137** [comment]
Did you mean you want ripple effect for ViewGroup like FrameLayout, LinearLayout, ...? Currently it isn't available, but you can easily create your custom layout that support ripple effect. Please follow **Ripple Effect for Custom View** section in [**Button**](https://github.com/rey5137/material/wiki/Button) page.

**Comment by Dengzer** [comment]
Thank you very much!
