### ISSUE TITLE
Spinner dropdown height is wrong

### ISSUE THREAD

**Issue by thomas76** [rey5137/material#88]
This shows in at least these two cases:

– In an activity, the bottom of the dropdown is hidden by the navigation bar, which is confusing.
* com.rey.material.widget.Spinner: https://cloud.githubusercontent.com/assets/12276153/7500654/3040e298-f42f-11e4-9347-812cce81d077.png
* android.widget.Spinner, for comparison: https://cloud.githubusercontent.com/assets/12276153/7500645/20a85be0-f42f-11e4-8024-b60bfb62569f.png

– In a dialog, the height of the dropdown is constrained by the height of the dialog instead of the height of the display, making it hard to use with small dialogs. And as can be seen in the following screenshots, the bottom is hidden too, by the spinner itself this time.
* com.rey.material.widget.Spinner: https://cloud.githubusercontent.com/assets/12276153/7500657/387842e4-f42f-11e4-9f68-03d3f3001f58.png
* android.widget.Spinner: https://cloud.githubusercontent.com/assets/12276153/7500656/3616b918-f42f-11e4-8934-b4790eb4241f.png

Easy to reproduce with a spinner containing a lot of items. For the first case, you need a device with a navigation bar (not with real navigations buttons).
Tried and reproduced on API 10 and 22.

**Comment by rey5137** [comment]
Which devices you use to reproduce this bugs? I try to do it on genymotion simulator but Spinner work fine.

**Comment by thomas76** [comment]
Well, I checked and the first problem seems to happen only on Lollipop. I reproduced it with Genymotion on a nexus10 with API 22, but not on a nexus 4 with API 19.

The second problem (in a dialog) I can reproduct on any version, though. (These are actually two distinct problems, I should have open two issues, sorry for that.)
