### ISSUE TITLE
TimePickerDialog - change format

### ISSUE THREAD

**Issue by Ein6tein** [rey5137/material#93]
Cannot find feature to switch time format from 12-hour with AM-PM to 24-hour. Is there any? If no, would be very useful to have one, wouldn't it?

**Comment by rey5137** [comment]
I added this feature in dev branch. Will available in next version.

**Comment by Ein6tein** [comment]
May I ask, when next version will be available? :) because I'm using Your great library for my diploma work, and this particular feature would be very useful for it :)

**Comment by rey5137** [comment]
For now, you can try out the `1.1.1-SNAPSHOT` version.

**Comment by rey5137** [comment]
I have released `1.1.1` version. You can use `tp_24Hour` attribute to switch the time format. Please view [Picker](https://github.com/rey5137/material/wiki/Picker) page for more details.
