### ISSUE TITLE
Callback when Snackbar hides itself when shown for a particular duration?

### ISSUE THREAD

**Issue by anupsarode** [rey5137/material#99]
Hello,

I'm showing the snackbar for 2 seconds using the following code.

SnackBar snackbar = SnackBar.make(this).applyStyle(R.style.SnackBarSingleLine);
snackbar.text("Some Text")
                        .singleLine(true)
                        .duration(2000)
                        .show(this);

When the snackbar hides itself, is there any callback that I get to do other things?

**Comment by rey5137** [comment]
You can call `stateChangeListener(SnackBar.OnStateChangeListener)` method to register a listener that will be called when SnackBar's state is changed. There're 4 states: **STATE_DISMISSED**, **STATE_SHOWED**, **STATE_DIMISSING** and **STATE_SHOWING**.

**Comment by anupsarode** [comment]
Hello Rey,

Thanks for your inputs. It worked. Following is the working code for anybody else who is seeking for this.

SnackBar snackbar = SnackBar.make(this).applyStyle(R.style.SnackBarSingleLine);
snackbar.text("Some Text")
.stateChangeListener(new SnackBar.OnStateChangeListener()
{
     public void onStateChange(SnackBar sb, int oldState, int newState)
     {
          // Your code here
     }
})
.singleLine(true)
.duration(2000)
.show(this);
